/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcceptInvitationIntent {
    /// Unique identifier for a given Invitation object.
    #[serde(rename = "invitationId")]
    pub invitation_id: String,
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "authenticator")]
    pub authenticator: Box<models::AuthenticatorParams>,
}

impl AcceptInvitationIntent {
    pub fn new(invitation_id: String, user_id: String, authenticator: models::AuthenticatorParams) -> AcceptInvitationIntent {
        AcceptInvitationIntent {
            invitation_id,
            user_id,
            authenticator: Box::new(authenticator),
        }
    }
}

