/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccessType {
    #[serde(rename = "ACCESS_TYPE_WEB")]
    AccessTypeWeb,
    #[serde(rename = "ACCESS_TYPE_API")]
    AccessTypeApi,
    #[serde(rename = "ACCESS_TYPE_ALL")]
    AccessTypeAll,

}

impl std::fmt::Display for AccessType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AccessTypeWeb => write!(f, "ACCESS_TYPE_WEB"),
            Self::AccessTypeApi => write!(f, "ACCESS_TYPE_API"),
            Self::AccessTypeAll => write!(f, "ACCESS_TYPE_ALL"),
        }
    }
}

impl Default for AccessType {
    fn default() -> AccessType {
        Self::AccessTypeWeb
    }
}

