/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivateBillingTierIntent {
    /// The product that the customer wants to subscribe to.
    #[serde(rename = "productId")]
    pub product_id: String,
}

impl ActivateBillingTierIntent {
    pub fn new(product_id: String) -> ActivateBillingTierIntent {
        ActivateBillingTierIntent {
            product_id,
        }
    }
}

