/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActivityStatus {
    #[serde(rename = "ACTIVITY_STATUS_CREATED")]
    ActivityStatusCreated,
    #[serde(rename = "ACTIVITY_STATUS_PENDING")]
    ActivityStatusPending,
    #[serde(rename = "ACTIVITY_STATUS_COMPLETED")]
    ActivityStatusCompleted,
    #[serde(rename = "ACTIVITY_STATUS_FAILED")]
    ActivityStatusFailed,
    #[serde(rename = "ACTIVITY_STATUS_CONSENSUS_NEEDED")]
    ActivityStatusConsensusNeeded,
    #[serde(rename = "ACTIVITY_STATUS_REJECTED")]
    ActivityStatusRejected,

}

impl std::fmt::Display for ActivityStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ActivityStatusCreated => write!(f, "ACTIVITY_STATUS_CREATED"),
            Self::ActivityStatusPending => write!(f, "ACTIVITY_STATUS_PENDING"),
            Self::ActivityStatusCompleted => write!(f, "ACTIVITY_STATUS_COMPLETED"),
            Self::ActivityStatusFailed => write!(f, "ACTIVITY_STATUS_FAILED"),
            Self::ActivityStatusConsensusNeeded => write!(f, "ACTIVITY_STATUS_CONSENSUS_NEEDED"),
            Self::ActivityStatusRejected => write!(f, "ACTIVITY_STATUS_REJECTED"),
        }
    }
}

impl Default for ActivityStatus {
    fn default() -> ActivityStatus {
        Self::ActivityStatusCreated
    }
}

