/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityResponse {
    #[serde(rename = "activity")]
    pub activity: Box<models::Activity>,
}

impl ActivityResponse {
    pub fn new(activity: models::Activity) -> ActivityResponse {
        ActivityResponse {
            activity: Box::new(activity),
        }
    }
}

