/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityPeriodV1PeriodAddress {
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<models::AddressFormat>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
}

impl ActivityPeriodV1PeriodAddress {
    pub fn new() -> ActivityPeriodV1PeriodAddress {
        ActivityPeriodV1PeriodAddress {
            format: None,
            address: None,
        }
    }
}

