/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Activity {
    /// Unique identifier for a given Activity object.
    #[serde(rename = "id")]
    pub id: String,
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    #[serde(rename = "status")]
    pub status: models::ActivityStatus,
    #[serde(rename = "type")]
    pub r#type: models::ActivityType,
    #[serde(rename = "intent")]
    pub intent: Box<models::Intent>,
    #[serde(rename = "result")]
    pub result: Box<models::Result>,
    /// A list of objects representing a particular User's approval or rejection of a Consensus request, including all relevant metadata.
    #[serde(rename = "votes")]
    pub votes: Vec<models::Vote>,
    /// An artifact verifying a User's action.
    #[serde(rename = "fingerprint")]
    pub fingerprint: String,
    #[serde(rename = "canApprove")]
    pub can_approve: bool,
    #[serde(rename = "canReject")]
    pub can_reject: bool,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "failure", skip_serializing_if = "Option::is_none")]
    pub failure: Option<Box<models::Status>>,
}

impl Activity {
    pub fn new(id: String, organization_id: String, status: models::ActivityStatus, r#type: models::ActivityType, intent: models::Intent, result: models::Result, votes: Vec<models::Vote>, fingerprint: String, can_approve: bool, can_reject: bool, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, updated_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp) -> Activity {
        Activity {
            id,
            organization_id,
            status,
            r#type,
            intent: Box::new(intent),
            result: Box::new(result),
            votes,
            fingerprint,
            can_approve,
            can_reject,
            created_at: Box::new(created_at),
            updated_at: Box::new(updated_at),
            failure: None,
        }
    }
}

