/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActivityType {
    #[serde(rename = "ACTIVITY_TYPE_CREATE_API_KEYS")]
    ActivityTypeCreateApiKeys,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_USERS")]
    ActivityTypeCreateUsers,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS")]
    ActivityTypeCreatePrivateKeys,
    #[serde(rename = "ACTIVITY_TYPE_SIGN_RAW_PAYLOAD")]
    ActivityTypeSignRawPayload,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_INVITATIONS")]
    ActivityTypeCreateInvitations,
    #[serde(rename = "ACTIVITY_TYPE_ACCEPT_INVITATION")]
    ActivityTypeAcceptInvitation,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_POLICY")]
    ActivityTypeCreatePolicy,
    #[serde(rename = "ACTIVITY_TYPE_DISABLE_PRIVATE_KEY")]
    ActivityTypeDisablePrivateKey,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_USERS")]
    ActivityTypeDeleteUsers,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_API_KEYS")]
    ActivityTypeDeleteApiKeys,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_INVITATION")]
    ActivityTypeDeleteInvitation,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_ORGANIZATION")]
    ActivityTypeDeleteOrganization,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_POLICY")]
    ActivityTypeDeletePolicy,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_USER_TAG")]
    ActivityTypeCreateUserTag,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_USER_TAGS")]
    ActivityTypeDeleteUserTags,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_ORGANIZATION")]
    ActivityTypeCreateOrganization,
    #[serde(rename = "ACTIVITY_TYPE_SIGN_TRANSACTION")]
    ActivityTypeSignTransaction,
    #[serde(rename = "ACTIVITY_TYPE_APPROVE_ACTIVITY")]
    ActivityTypeApproveActivity,
    #[serde(rename = "ACTIVITY_TYPE_REJECT_ACTIVITY")]
    ActivityTypeRejectActivity,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_AUTHENTICATORS")]
    ActivityTypeDeleteAuthenticators,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_AUTHENTICATORS")]
    ActivityTypeCreateAuthenticators,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_PRIVATE_KEY_TAG")]
    ActivityTypeCreatePrivateKeyTag,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_PRIVATE_KEY_TAGS")]
    ActivityTypeDeletePrivateKeyTags,
    #[serde(rename = "ACTIVITY_TYPE_SET_PAYMENT_METHOD")]
    ActivityTypeSetPaymentMethod,
    #[serde(rename = "ACTIVITY_TYPE_ACTIVATE_BILLING_TIER")]
    ActivityTypeActivateBillingTier,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_PAYMENT_METHOD")]
    ActivityTypeDeletePaymentMethod,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_POLICY_V2")]
    ActivityTypeCreatePolicyV2,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_POLICY_V3")]
    ActivityTypeCreatePolicyV3,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_API_ONLY_USERS")]
    ActivityTypeCreateApiOnlyUsers,
    #[serde(rename = "ACTIVITY_TYPE_UPDATE_ROOT_QUORUM")]
    ActivityTypeUpdateRootQuorum,
    #[serde(rename = "ACTIVITY_TYPE_UPDATE_USER_TAG")]
    ActivityTypeUpdateUserTag,
    #[serde(rename = "ACTIVITY_TYPE_UPDATE_PRIVATE_KEY_TAG")]
    ActivityTypeUpdatePrivateKeyTag,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_AUTHENTICATORS_V2")]
    ActivityTypeCreateAuthenticatorsV2,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_ORGANIZATION_V2")]
    ActivityTypeCreateOrganizationV2,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_USERS_V2")]
    ActivityTypeCreateUsersV2,
    #[serde(rename = "ACTIVITY_TYPE_ACCEPT_INVITATION_V2")]
    ActivityTypeAcceptInvitationV2,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION")]
    ActivityTypeCreateSubOrganization,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V2")]
    ActivityTypeCreateSubOrganizationV2,
    #[serde(rename = "ACTIVITY_TYPE_UPDATE_ALLOWED_ORIGINS")]
    ActivityTypeUpdateAllowedOrigins,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2")]
    ActivityTypeCreatePrivateKeysV2,
    #[serde(rename = "ACTIVITY_TYPE_UPDATE_USER")]
    ActivityTypeUpdateUser,
    #[serde(rename = "ACTIVITY_TYPE_UPDATE_POLICY")]
    ActivityTypeUpdatePolicy,
    #[serde(rename = "ACTIVITY_TYPE_SET_PAYMENT_METHOD_V2")]
    ActivityTypeSetPaymentMethodV2,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V3")]
    ActivityTypeCreateSubOrganizationV3,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_WALLET")]
    ActivityTypeCreateWallet,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_WALLET_ACCOUNTS")]
    ActivityTypeCreateWalletAccounts,
    #[serde(rename = "ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY")]
    ActivityTypeInitUserEmailRecovery,
    #[serde(rename = "ACTIVITY_TYPE_RECOVER_USER")]
    ActivityTypeRecoverUser,
    #[serde(rename = "ACTIVITY_TYPE_SET_ORGANIZATION_FEATURE")]
    ActivityTypeSetOrganizationFeature,
    #[serde(rename = "ACTIVITY_TYPE_REMOVE_ORGANIZATION_FEATURE")]
    ActivityTypeRemoveOrganizationFeature,
    #[serde(rename = "ACTIVITY_TYPE_SIGN_RAW_PAYLOAD_V2")]
    ActivityTypeSignRawPayloadV2,
    #[serde(rename = "ACTIVITY_TYPE_SIGN_TRANSACTION_V2")]
    ActivityTypeSignTransactionV2,
    #[serde(rename = "ACTIVITY_TYPE_EXPORT_PRIVATE_KEY")]
    ActivityTypeExportPrivateKey,
    #[serde(rename = "ACTIVITY_TYPE_EXPORT_WALLET")]
    ActivityTypeExportWallet,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V4")]
    ActivityTypeCreateSubOrganizationV4,
    #[serde(rename = "ACTIVITY_TYPE_EMAIL_AUTH")]
    ActivityTypeEmailAuth,
    #[serde(rename = "ACTIVITY_TYPE_EXPORT_WALLET_ACCOUNT")]
    ActivityTypeExportWalletAccount,
    #[serde(rename = "ACTIVITY_TYPE_INIT_IMPORT_WALLET")]
    ActivityTypeInitImportWallet,
    #[serde(rename = "ACTIVITY_TYPE_IMPORT_WALLET")]
    ActivityTypeImportWallet,
    #[serde(rename = "ACTIVITY_TYPE_INIT_IMPORT_PRIVATE_KEY")]
    ActivityTypeInitImportPrivateKey,
    #[serde(rename = "ACTIVITY_TYPE_IMPORT_PRIVATE_KEY")]
    ActivityTypeImportPrivateKey,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_POLICIES")]
    ActivityTypeCreatePolicies,
    #[serde(rename = "ACTIVITY_TYPE_SIGN_RAW_PAYLOADS")]
    ActivityTypeSignRawPayloads,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_READ_ONLY_SESSION")]
    ActivityTypeCreateReadOnlySession,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_OAUTH_PROVIDERS")]
    ActivityTypeCreateOauthProviders,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_OAUTH_PROVIDERS")]
    ActivityTypeDeleteOauthProviders,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V5")]
    ActivityTypeCreateSubOrganizationV5,
    #[serde(rename = "ACTIVITY_TYPE_OAUTH")]
    ActivityTypeOauth,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_API_KEYS_V2")]
    ActivityTypeCreateApiKeysV2,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION")]
    ActivityTypeCreateReadWriteSession,
    #[serde(rename = "ACTIVITY_TYPE_EMAIL_AUTH_V2")]
    ActivityTypeEmailAuthV2,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V6")]
    ActivityTypeCreateSubOrganizationV6,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_PRIVATE_KEYS")]
    ActivityTypeDeletePrivateKeys,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_WALLETS")]
    ActivityTypeDeleteWallets,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION_V2")]
    ActivityTypeCreateReadWriteSessionV2,
    #[serde(rename = "ACTIVITY_TYPE_DELETE_SUB_ORGANIZATION")]
    ActivityTypeDeleteSubOrganization,
    #[serde(rename = "ACTIVITY_TYPE_INIT_OTP_AUTH")]
    ActivityTypeInitOtpAuth,
    #[serde(rename = "ACTIVITY_TYPE_OTP_AUTH")]
    ActivityTypeOtpAuth,
    #[serde(rename = "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V7")]
    ActivityTypeCreateSubOrganizationV7,
    #[serde(rename = "ACTIVITY_TYPE_UPDATE_WALLET")]
    ActivityTypeUpdateWallet,

}

impl std::fmt::Display for ActivityType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ActivityTypeCreateApiKeys => write!(f, "ACTIVITY_TYPE_CREATE_API_KEYS"),
            Self::ActivityTypeCreateUsers => write!(f, "ACTIVITY_TYPE_CREATE_USERS"),
            Self::ActivityTypeCreatePrivateKeys => write!(f, "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS"),
            Self::ActivityTypeSignRawPayload => write!(f, "ACTIVITY_TYPE_SIGN_RAW_PAYLOAD"),
            Self::ActivityTypeCreateInvitations => write!(f, "ACTIVITY_TYPE_CREATE_INVITATIONS"),
            Self::ActivityTypeAcceptInvitation => write!(f, "ACTIVITY_TYPE_ACCEPT_INVITATION"),
            Self::ActivityTypeCreatePolicy => write!(f, "ACTIVITY_TYPE_CREATE_POLICY"),
            Self::ActivityTypeDisablePrivateKey => write!(f, "ACTIVITY_TYPE_DISABLE_PRIVATE_KEY"),
            Self::ActivityTypeDeleteUsers => write!(f, "ACTIVITY_TYPE_DELETE_USERS"),
            Self::ActivityTypeDeleteApiKeys => write!(f, "ACTIVITY_TYPE_DELETE_API_KEYS"),
            Self::ActivityTypeDeleteInvitation => write!(f, "ACTIVITY_TYPE_DELETE_INVITATION"),
            Self::ActivityTypeDeleteOrganization => write!(f, "ACTIVITY_TYPE_DELETE_ORGANIZATION"),
            Self::ActivityTypeDeletePolicy => write!(f, "ACTIVITY_TYPE_DELETE_POLICY"),
            Self::ActivityTypeCreateUserTag => write!(f, "ACTIVITY_TYPE_CREATE_USER_TAG"),
            Self::ActivityTypeDeleteUserTags => write!(f, "ACTIVITY_TYPE_DELETE_USER_TAGS"),
            Self::ActivityTypeCreateOrganization => write!(f, "ACTIVITY_TYPE_CREATE_ORGANIZATION"),
            Self::ActivityTypeSignTransaction => write!(f, "ACTIVITY_TYPE_SIGN_TRANSACTION"),
            Self::ActivityTypeApproveActivity => write!(f, "ACTIVITY_TYPE_APPROVE_ACTIVITY"),
            Self::ActivityTypeRejectActivity => write!(f, "ACTIVITY_TYPE_REJECT_ACTIVITY"),
            Self::ActivityTypeDeleteAuthenticators => write!(f, "ACTIVITY_TYPE_DELETE_AUTHENTICATORS"),
            Self::ActivityTypeCreateAuthenticators => write!(f, "ACTIVITY_TYPE_CREATE_AUTHENTICATORS"),
            Self::ActivityTypeCreatePrivateKeyTag => write!(f, "ACTIVITY_TYPE_CREATE_PRIVATE_KEY_TAG"),
            Self::ActivityTypeDeletePrivateKeyTags => write!(f, "ACTIVITY_TYPE_DELETE_PRIVATE_KEY_TAGS"),
            Self::ActivityTypeSetPaymentMethod => write!(f, "ACTIVITY_TYPE_SET_PAYMENT_METHOD"),
            Self::ActivityTypeActivateBillingTier => write!(f, "ACTIVITY_TYPE_ACTIVATE_BILLING_TIER"),
            Self::ActivityTypeDeletePaymentMethod => write!(f, "ACTIVITY_TYPE_DELETE_PAYMENT_METHOD"),
            Self::ActivityTypeCreatePolicyV2 => write!(f, "ACTIVITY_TYPE_CREATE_POLICY_V2"),
            Self::ActivityTypeCreatePolicyV3 => write!(f, "ACTIVITY_TYPE_CREATE_POLICY_V3"),
            Self::ActivityTypeCreateApiOnlyUsers => write!(f, "ACTIVITY_TYPE_CREATE_API_ONLY_USERS"),
            Self::ActivityTypeUpdateRootQuorum => write!(f, "ACTIVITY_TYPE_UPDATE_ROOT_QUORUM"),
            Self::ActivityTypeUpdateUserTag => write!(f, "ACTIVITY_TYPE_UPDATE_USER_TAG"),
            Self::ActivityTypeUpdatePrivateKeyTag => write!(f, "ACTIVITY_TYPE_UPDATE_PRIVATE_KEY_TAG"),
            Self::ActivityTypeCreateAuthenticatorsV2 => write!(f, "ACTIVITY_TYPE_CREATE_AUTHENTICATORS_V2"),
            Self::ActivityTypeCreateOrganizationV2 => write!(f, "ACTIVITY_TYPE_CREATE_ORGANIZATION_V2"),
            Self::ActivityTypeCreateUsersV2 => write!(f, "ACTIVITY_TYPE_CREATE_USERS_V2"),
            Self::ActivityTypeAcceptInvitationV2 => write!(f, "ACTIVITY_TYPE_ACCEPT_INVITATION_V2"),
            Self::ActivityTypeCreateSubOrganization => write!(f, "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION"),
            Self::ActivityTypeCreateSubOrganizationV2 => write!(f, "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V2"),
            Self::ActivityTypeUpdateAllowedOrigins => write!(f, "ACTIVITY_TYPE_UPDATE_ALLOWED_ORIGINS"),
            Self::ActivityTypeCreatePrivateKeysV2 => write!(f, "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2"),
            Self::ActivityTypeUpdateUser => write!(f, "ACTIVITY_TYPE_UPDATE_USER"),
            Self::ActivityTypeUpdatePolicy => write!(f, "ACTIVITY_TYPE_UPDATE_POLICY"),
            Self::ActivityTypeSetPaymentMethodV2 => write!(f, "ACTIVITY_TYPE_SET_PAYMENT_METHOD_V2"),
            Self::ActivityTypeCreateSubOrganizationV3 => write!(f, "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V3"),
            Self::ActivityTypeCreateWallet => write!(f, "ACTIVITY_TYPE_CREATE_WALLET"),
            Self::ActivityTypeCreateWalletAccounts => write!(f, "ACTIVITY_TYPE_CREATE_WALLET_ACCOUNTS"),
            Self::ActivityTypeInitUserEmailRecovery => write!(f, "ACTIVITY_TYPE_INIT_USER_EMAIL_RECOVERY"),
            Self::ActivityTypeRecoverUser => write!(f, "ACTIVITY_TYPE_RECOVER_USER"),
            Self::ActivityTypeSetOrganizationFeature => write!(f, "ACTIVITY_TYPE_SET_ORGANIZATION_FEATURE"),
            Self::ActivityTypeRemoveOrganizationFeature => write!(f, "ACTIVITY_TYPE_REMOVE_ORGANIZATION_FEATURE"),
            Self::ActivityTypeSignRawPayloadV2 => write!(f, "ACTIVITY_TYPE_SIGN_RAW_PAYLOAD_V2"),
            Self::ActivityTypeSignTransactionV2 => write!(f, "ACTIVITY_TYPE_SIGN_TRANSACTION_V2"),
            Self::ActivityTypeExportPrivateKey => write!(f, "ACTIVITY_TYPE_EXPORT_PRIVATE_KEY"),
            Self::ActivityTypeExportWallet => write!(f, "ACTIVITY_TYPE_EXPORT_WALLET"),
            Self::ActivityTypeCreateSubOrganizationV4 => write!(f, "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V4"),
            Self::ActivityTypeEmailAuth => write!(f, "ACTIVITY_TYPE_EMAIL_AUTH"),
            Self::ActivityTypeExportWalletAccount => write!(f, "ACTIVITY_TYPE_EXPORT_WALLET_ACCOUNT"),
            Self::ActivityTypeInitImportWallet => write!(f, "ACTIVITY_TYPE_INIT_IMPORT_WALLET"),
            Self::ActivityTypeImportWallet => write!(f, "ACTIVITY_TYPE_IMPORT_WALLET"),
            Self::ActivityTypeInitImportPrivateKey => write!(f, "ACTIVITY_TYPE_INIT_IMPORT_PRIVATE_KEY"),
            Self::ActivityTypeImportPrivateKey => write!(f, "ACTIVITY_TYPE_IMPORT_PRIVATE_KEY"),
            Self::ActivityTypeCreatePolicies => write!(f, "ACTIVITY_TYPE_CREATE_POLICIES"),
            Self::ActivityTypeSignRawPayloads => write!(f, "ACTIVITY_TYPE_SIGN_RAW_PAYLOADS"),
            Self::ActivityTypeCreateReadOnlySession => write!(f, "ACTIVITY_TYPE_CREATE_READ_ONLY_SESSION"),
            Self::ActivityTypeCreateOauthProviders => write!(f, "ACTIVITY_TYPE_CREATE_OAUTH_PROVIDERS"),
            Self::ActivityTypeDeleteOauthProviders => write!(f, "ACTIVITY_TYPE_DELETE_OAUTH_PROVIDERS"),
            Self::ActivityTypeCreateSubOrganizationV5 => write!(f, "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V5"),
            Self::ActivityTypeOauth => write!(f, "ACTIVITY_TYPE_OAUTH"),
            Self::ActivityTypeCreateApiKeysV2 => write!(f, "ACTIVITY_TYPE_CREATE_API_KEYS_V2"),
            Self::ActivityTypeCreateReadWriteSession => write!(f, "ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION"),
            Self::ActivityTypeEmailAuthV2 => write!(f, "ACTIVITY_TYPE_EMAIL_AUTH_V2"),
            Self::ActivityTypeCreateSubOrganizationV6 => write!(f, "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V6"),
            Self::ActivityTypeDeletePrivateKeys => write!(f, "ACTIVITY_TYPE_DELETE_PRIVATE_KEYS"),
            Self::ActivityTypeDeleteWallets => write!(f, "ACTIVITY_TYPE_DELETE_WALLETS"),
            Self::ActivityTypeCreateReadWriteSessionV2 => write!(f, "ACTIVITY_TYPE_CREATE_READ_WRITE_SESSION_V2"),
            Self::ActivityTypeDeleteSubOrganization => write!(f, "ACTIVITY_TYPE_DELETE_SUB_ORGANIZATION"),
            Self::ActivityTypeInitOtpAuth => write!(f, "ACTIVITY_TYPE_INIT_OTP_AUTH"),
            Self::ActivityTypeOtpAuth => write!(f, "ACTIVITY_TYPE_OTP_AUTH"),
            Self::ActivityTypeCreateSubOrganizationV7 => write!(f, "ACTIVITY_TYPE_CREATE_SUB_ORGANIZATION_V7"),
            Self::ActivityTypeUpdateWallet => write!(f, "ACTIVITY_TYPE_UPDATE_WALLET"),
        }
    }
}

impl Default for ActivityType {
    fn default() -> ActivityType {
        Self::ActivityTypeCreateApiKeys
    }
}

