/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AddressFormat {
    #[serde(rename = "ADDRESS_FORMAT_UNCOMPRESSED")]
    AddressFormatUncompressed,
    #[serde(rename = "ADDRESS_FORMAT_COMPRESSED")]
    AddressFormatCompressed,
    #[serde(rename = "ADDRESS_FORMAT_ETHEREUM")]
    AddressFormatEthereum,
    #[serde(rename = "ADDRESS_FORMAT_SOLANA")]
    AddressFormatSolana,
    #[serde(rename = "ADDRESS_FORMAT_COSMOS")]
    AddressFormatCosmos,
    #[serde(rename = "ADDRESS_FORMAT_TRON")]
    AddressFormatTron,
    #[serde(rename = "ADDRESS_FORMAT_SUI")]
    AddressFormatSui,
    #[serde(rename = "ADDRESS_FORMAT_APTOS")]
    AddressFormatAptos,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_MAINNET_P2PKH")]
    AddressFormatBitcoinMainnetP2Pkh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_MAINNET_P2SH")]
    AddressFormatBitcoinMainnetP2Sh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_MAINNET_P2WPKH")]
    AddressFormatBitcoinMainnetP2Wpkh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_MAINNET_P2WSH")]
    AddressFormatBitcoinMainnetP2Wsh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_MAINNET_P2TR")]
    AddressFormatBitcoinMainnetP2Tr,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_TESTNET_P2PKH")]
    AddressFormatBitcoinTestnetP2Pkh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_TESTNET_P2SH")]
    AddressFormatBitcoinTestnetP2Sh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_TESTNET_P2WPKH")]
    AddressFormatBitcoinTestnetP2Wpkh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_TESTNET_P2WSH")]
    AddressFormatBitcoinTestnetP2Wsh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_TESTNET_P2TR")]
    AddressFormatBitcoinTestnetP2Tr,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_SIGNET_P2PKH")]
    AddressFormatBitcoinSignetP2Pkh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_SIGNET_P2SH")]
    AddressFormatBitcoinSignetP2Sh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_SIGNET_P2WPKH")]
    AddressFormatBitcoinSignetP2Wpkh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_SIGNET_P2WSH")]
    AddressFormatBitcoinSignetP2Wsh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_SIGNET_P2TR")]
    AddressFormatBitcoinSignetP2Tr,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_REGTEST_P2PKH")]
    AddressFormatBitcoinRegtestP2Pkh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_REGTEST_P2SH")]
    AddressFormatBitcoinRegtestP2Sh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_REGTEST_P2WPKH")]
    AddressFormatBitcoinRegtestP2Wpkh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_REGTEST_P2WSH")]
    AddressFormatBitcoinRegtestP2Wsh,
    #[serde(rename = "ADDRESS_FORMAT_BITCOIN_REGTEST_P2TR")]
    AddressFormatBitcoinRegtestP2Tr,
    #[serde(rename = "ADDRESS_FORMAT_SEI")]
    AddressFormatSei,
    #[serde(rename = "ADDRESS_FORMAT_XLM")]
    AddressFormatXlm,
    #[serde(rename = "ADDRESS_FORMAT_DOGE_MAINNET")]
    AddressFormatDogeMainnet,
    #[serde(rename = "ADDRESS_FORMAT_DOGE_TESTNET")]
    AddressFormatDogeTestnet,
    #[serde(rename = "ADDRESS_FORMAT_TON_V3R2")]
    AddressFormatTonV3R2,
    #[serde(rename = "ADDRESS_FORMAT_TON_V4R2")]
    AddressFormatTonV4R2,
    #[serde(rename = "ADDRESS_FORMAT_XRP")]
    AddressFormatXrp,

}

impl std::fmt::Display for AddressFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AddressFormatUncompressed => write!(f, "ADDRESS_FORMAT_UNCOMPRESSED"),
            Self::AddressFormatCompressed => write!(f, "ADDRESS_FORMAT_COMPRESSED"),
            Self::AddressFormatEthereum => write!(f, "ADDRESS_FORMAT_ETHEREUM"),
            Self::AddressFormatSolana => write!(f, "ADDRESS_FORMAT_SOLANA"),
            Self::AddressFormatCosmos => write!(f, "ADDRESS_FORMAT_COSMOS"),
            Self::AddressFormatTron => write!(f, "ADDRESS_FORMAT_TRON"),
            Self::AddressFormatSui => write!(f, "ADDRESS_FORMAT_SUI"),
            Self::AddressFormatAptos => write!(f, "ADDRESS_FORMAT_APTOS"),
            Self::AddressFormatBitcoinMainnetP2Pkh => write!(f, "ADDRESS_FORMAT_BITCOIN_MAINNET_P2PKH"),
            Self::AddressFormatBitcoinMainnetP2Sh => write!(f, "ADDRESS_FORMAT_BITCOIN_MAINNET_P2SH"),
            Self::AddressFormatBitcoinMainnetP2Wpkh => write!(f, "ADDRESS_FORMAT_BITCOIN_MAINNET_P2WPKH"),
            Self::AddressFormatBitcoinMainnetP2Wsh => write!(f, "ADDRESS_FORMAT_BITCOIN_MAINNET_P2WSH"),
            Self::AddressFormatBitcoinMainnetP2Tr => write!(f, "ADDRESS_FORMAT_BITCOIN_MAINNET_P2TR"),
            Self::AddressFormatBitcoinTestnetP2Pkh => write!(f, "ADDRESS_FORMAT_BITCOIN_TESTNET_P2PKH"),
            Self::AddressFormatBitcoinTestnetP2Sh => write!(f, "ADDRESS_FORMAT_BITCOIN_TESTNET_P2SH"),
            Self::AddressFormatBitcoinTestnetP2Wpkh => write!(f, "ADDRESS_FORMAT_BITCOIN_TESTNET_P2WPKH"),
            Self::AddressFormatBitcoinTestnetP2Wsh => write!(f, "ADDRESS_FORMAT_BITCOIN_TESTNET_P2WSH"),
            Self::AddressFormatBitcoinTestnetP2Tr => write!(f, "ADDRESS_FORMAT_BITCOIN_TESTNET_P2TR"),
            Self::AddressFormatBitcoinSignetP2Pkh => write!(f, "ADDRESS_FORMAT_BITCOIN_SIGNET_P2PKH"),
            Self::AddressFormatBitcoinSignetP2Sh => write!(f, "ADDRESS_FORMAT_BITCOIN_SIGNET_P2SH"),
            Self::AddressFormatBitcoinSignetP2Wpkh => write!(f, "ADDRESS_FORMAT_BITCOIN_SIGNET_P2WPKH"),
            Self::AddressFormatBitcoinSignetP2Wsh => write!(f, "ADDRESS_FORMAT_BITCOIN_SIGNET_P2WSH"),
            Self::AddressFormatBitcoinSignetP2Tr => write!(f, "ADDRESS_FORMAT_BITCOIN_SIGNET_P2TR"),
            Self::AddressFormatBitcoinRegtestP2Pkh => write!(f, "ADDRESS_FORMAT_BITCOIN_REGTEST_P2PKH"),
            Self::AddressFormatBitcoinRegtestP2Sh => write!(f, "ADDRESS_FORMAT_BITCOIN_REGTEST_P2SH"),
            Self::AddressFormatBitcoinRegtestP2Wpkh => write!(f, "ADDRESS_FORMAT_BITCOIN_REGTEST_P2WPKH"),
            Self::AddressFormatBitcoinRegtestP2Wsh => write!(f, "ADDRESS_FORMAT_BITCOIN_REGTEST_P2WSH"),
            Self::AddressFormatBitcoinRegtestP2Tr => write!(f, "ADDRESS_FORMAT_BITCOIN_REGTEST_P2TR"),
            Self::AddressFormatSei => write!(f, "ADDRESS_FORMAT_SEI"),
            Self::AddressFormatXlm => write!(f, "ADDRESS_FORMAT_XLM"),
            Self::AddressFormatDogeMainnet => write!(f, "ADDRESS_FORMAT_DOGE_MAINNET"),
            Self::AddressFormatDogeTestnet => write!(f, "ADDRESS_FORMAT_DOGE_TESTNET"),
            Self::AddressFormatTonV3R2 => write!(f, "ADDRESS_FORMAT_TON_V3R2"),
            Self::AddressFormatTonV4R2 => write!(f, "ADDRESS_FORMAT_TON_V4R2"),
            Self::AddressFormatXrp => write!(f, "ADDRESS_FORMAT_XRP"),
        }
    }
}

impl Default for AddressFormat {
    fn default() -> AddressFormat {
        Self::AddressFormatUncompressed
    }
}

