/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiOnlyUserParams {
    /// The name of the new API-only User.
    #[serde(rename = "userName")]
    pub user_name: String,
    /// The email address for this API-only User (optional).
    #[serde(rename = "userEmail", skip_serializing_if = "Option::is_none")]
    pub user_email: Option<String>,
    /// A list of tags assigned to the new API-only User.
    #[serde(rename = "userTags")]
    pub user_tags: Vec<String>,
    /// A list of API Key parameters.
    #[serde(rename = "apiKeys")]
    pub api_keys: Vec<models::ApiKeyParams>,
}

impl ApiOnlyUserParams {
    pub fn new(user_name: String, user_tags: Vec<String>, api_keys: Vec<models::ApiKeyParams>) -> ApiOnlyUserParams {
        ApiOnlyUserParams {
            user_name,
            user_email: None,
            user_tags,
            api_keys,
        }
    }
}

