/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyParamsV2 {
    /// Human-readable name for an API Key.
    #[serde(rename = "apiKeyName")]
    pub api_key_name: String,
    /// The public component of a cryptographic key pair used to sign messages and transactions.
    #[serde(rename = "publicKey")]
    pub public_key: String,
    #[serde(rename = "curveType")]
    pub curve_type: models::ApiKeyCurve,
    /// Optional window (in seconds) indicating how long the API Key should last.
    #[serde(rename = "expirationSeconds", skip_serializing_if = "Option::is_none")]
    pub expiration_seconds: Option<String>,
}

impl ApiKeyParamsV2 {
    pub fn new(api_key_name: String, public_key: String, curve_type: models::ApiKeyCurve) -> ApiKeyParamsV2 {
        ApiKeyParamsV2 {
            api_key_name,
            public_key,
            curve_type,
            expiration_seconds: None,
        }
    }
}

