/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKey {
    #[serde(rename = "credential")]
    pub credential: Box<models::ExternalPeriodDataPeriodV1PeriodCredential>,
    /// Unique identifier for a given API Key.
    #[serde(rename = "apiKeyId")]
    pub api_key_id: String,
    /// Human-readable name for an API Key.
    #[serde(rename = "apiKeyName")]
    pub api_key_name: String,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    /// Optional window (in seconds) indicating how long the API Key should last.
    #[serde(rename = "expirationSeconds", skip_serializing_if = "Option::is_none")]
    pub expiration_seconds: Option<String>,
}

impl ApiKey {
    pub fn new(credential: models::ExternalPeriodDataPeriodV1PeriodCredential, api_key_id: String, api_key_name: String, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, updated_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp) -> ApiKey {
        ApiKey {
            credential: Box::new(credential),
            api_key_id,
            api_key_name,
            created_at: Box::new(created_at),
            updated_at: Box::new(updated_at),
            expiration_seconds: None,
        }
    }
}

