/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiKeyCurve {
    #[serde(rename = "API_KEY_CURVE_P256")]
    ApiKeyCurveP256,
    #[serde(rename = "API_KEY_CURVE_SECP256K1")]
    ApiKeyCurveSecp256K1,
    #[serde(rename = "API_KEY_CURVE_ED25519")]
    ApiKeyCurveEd25519,

}

impl std::fmt::Display for ApiKeyCurve {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ApiKeyCurveP256 => write!(f, "API_KEY_CURVE_P256"),
            Self::ApiKeyCurveSecp256K1 => write!(f, "API_KEY_CURVE_SECP256K1"),
            Self::ApiKeyCurveEd25519 => write!(f, "API_KEY_CURVE_ED25519"),
        }
    }
}

impl Default for ApiKeyCurve {
    fn default() -> ApiKeyCurve {
        Self::ApiKeyCurveP256
    }
}

