/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApproveActivityIntent {
    /// An artifact verifying a User's action.
    #[serde(rename = "fingerprint")]
    pub fingerprint: String,
}

impl ApproveActivityIntent {
    pub fn new(fingerprint: String) -> ApproveActivityIntent {
        ApproveActivityIntent {
            fingerprint,
        }
    }
}

