/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Attestation {
    /// The cbor encoded then base64 url encoded id of the credential.
    #[serde(rename = "credentialId")]
    pub credential_id: String,
    /// A base64 url encoded payload containing metadata about the signing context and the challenge.
    #[serde(rename = "clientDataJson")]
    pub client_data_json: String,
    /// A base64 url encoded payload containing authenticator data and any attestation the webauthn provider chooses.
    #[serde(rename = "attestationObject")]
    pub attestation_object: String,
    /// The type of authenticator transports.
    #[serde(rename = "transports")]
    pub transports: Vec<models::AuthenticatorTransport>,
}

impl Attestation {
    pub fn new(credential_id: String, client_data_json: String, attestation_object: String, transports: Vec<models::AuthenticatorTransport>) -> Attestation {
        Attestation {
            credential_id,
            client_data_json,
            attestation_object,
            transports,
        }
    }
}

