/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Authenticator {
    /// Types of transports that may be used by an Authenticator (e.g., USB, NFC, BLE).
    #[serde(rename = "transports")]
    pub transports: Vec<models::AuthenticatorTransport>,
    #[serde(rename = "attestationType")]
    pub attestation_type: String,
    /// Identifier indicating the type of the Security Key.
    #[serde(rename = "aaguid")]
    pub aaguid: String,
    /// Unique identifier for a WebAuthn credential.
    #[serde(rename = "credentialId")]
    pub credential_id: String,
    /// The type of Authenticator device.
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "credential")]
    pub credential: Box<models::ExternalPeriodDataPeriodV1PeriodCredential>,
    /// Unique identifier for a given Authenticator.
    #[serde(rename = "authenticatorId")]
    pub authenticator_id: String,
    /// Human-readable name for an Authenticator.
    #[serde(rename = "authenticatorName")]
    pub authenticator_name: String,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
}

impl Authenticator {
    pub fn new(transports: Vec<models::AuthenticatorTransport>, attestation_type: String, aaguid: String, credential_id: String, model: String, credential: models::ExternalPeriodDataPeriodV1PeriodCredential, authenticator_id: String, authenticator_name: String, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, updated_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp) -> Authenticator {
        Authenticator {
            transports,
            attestation_type,
            aaguid,
            credential_id,
            model,
            credential: Box::new(credential),
            authenticator_id,
            authenticator_name,
            created_at: Box::new(created_at),
            updated_at: Box::new(updated_at),
        }
    }
}

