/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticatorTransport {
    #[serde(rename = "AUTHENTICATOR_TRANSPORT_BLE")]
    AuthenticatorTransportBle,
    #[serde(rename = "AUTHENTICATOR_TRANSPORT_INTERNAL")]
    AuthenticatorTransportInternal,
    #[serde(rename = "AUTHENTICATOR_TRANSPORT_NFC")]
    AuthenticatorTransportNfc,
    #[serde(rename = "AUTHENTICATOR_TRANSPORT_USB")]
    AuthenticatorTransportUsb,
    #[serde(rename = "AUTHENTICATOR_TRANSPORT_HYBRID")]
    AuthenticatorTransportHybrid,

}

impl std::fmt::Display for AuthenticatorTransport {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AuthenticatorTransportBle => write!(f, "AUTHENTICATOR_TRANSPORT_BLE"),
            Self::AuthenticatorTransportInternal => write!(f, "AUTHENTICATOR_TRANSPORT_INTERNAL"),
            Self::AuthenticatorTransportNfc => write!(f, "AUTHENTICATOR_TRANSPORT_NFC"),
            Self::AuthenticatorTransportUsb => write!(f, "AUTHENTICATOR_TRANSPORT_USB"),
            Self::AuthenticatorTransportHybrid => write!(f, "AUTHENTICATOR_TRANSPORT_HYBRID"),
        }
    }
}

impl Default for AuthenticatorTransport {
    fn default() -> AuthenticatorTransport {
        Self::AuthenticatorTransportBle
    }
}

