/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticatorParamsV2 {
    /// Human-readable name for an Authenticator.
    #[serde(rename = "authenticatorName")]
    pub authenticator_name: String,
    /// Challenge presented for authentication purposes.
    #[serde(rename = "challenge")]
    pub challenge: String,
    #[serde(rename = "attestation")]
    pub attestation: Box<models::Attestation>,
}

impl AuthenticatorParamsV2 {
    pub fn new(authenticator_name: String, challenge: String, attestation: models::Attestation) -> AuthenticatorParamsV2 {
        AuthenticatorParamsV2 {
            authenticator_name,
            challenge,
            attestation: Box::new(attestation),
        }
    }
}

