/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticatorParams {
    /// Human-readable name for an Authenticator.
    #[serde(rename = "authenticatorName")]
    pub authenticator_name: String,
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "attestation")]
    pub attestation: Box<models::PublicKeyCredentialWithAttestation>,
    /// Challenge presented for authentication purposes.
    #[serde(rename = "challenge")]
    pub challenge: String,
}

impl AuthenticatorParams {
    pub fn new(authenticator_name: String, user_id: String, attestation: models::PublicKeyCredentialWithAttestation, challenge: String) -> AuthenticatorParams {
        AuthenticatorParams {
            authenticator_name,
            user_id,
            attestation: Box::new(attestation),
            challenge,
        }
    }
}

