/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticatorAttestationResponse {
    #[serde(rename = "clientDataJson")]
    pub client_data_json: String,
    #[serde(rename = "attestationObject")]
    pub attestation_object: String,
    #[serde(rename = "transports", skip_serializing_if = "Option::is_none")]
    pub transports: Option<Vec<models::AuthenticatorTransport>>,
    #[serde(rename = "authenticatorAttachment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub authenticator_attachment: Option<Option<AuthenticatorAttachment>>,
}

impl AuthenticatorAttestationResponse {
    pub fn new(client_data_json: String, attestation_object: String) -> AuthenticatorAttestationResponse {
        AuthenticatorAttestationResponse {
            client_data_json,
            attestation_object,
            transports: None,
            authenticator_attachment: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticatorAttachment {
    #[serde(rename = "cross-platform")]
    CrossPlatform,
    #[serde(rename = "platform")]
    Platform,
}

impl Default for AuthenticatorAttachment {
    fn default() -> AuthenticatorAttachment {
        Self::CrossPlatform
    }
}

