/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Config {
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<models::Feature>>,
    #[serde(rename = "quorum", skip_serializing_if = "Option::is_none")]
    pub quorum: Option<Box<models::ExternalPeriodDataPeriodV1PeriodQuorum>>,
}

impl Config {
    pub fn new() -> Config {
        Config {
            features: None,
            quorum: None,
        }
    }
}

