/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUsersIntentV2 {
    /// A list of Users.
    #[serde(rename = "users")]
    pub users: Vec<models::UserParamsV2>,
}

impl CreateUsersIntentV2 {
    pub fn new(users: Vec<models::UserParamsV2>) -> CreateUsersIntentV2 {
        CreateUsersIntentV2 {
            users,
        }
    }
}

