/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserTagIntent {
    /// Human-readable name for a User Tag.
    #[serde(rename = "userTagName")]
    pub user_tag_name: String,
    /// A list of User IDs.
    #[serde(rename = "userIds")]
    pub user_ids: Vec<String>,
}

impl CreateUserTagIntent {
    pub fn new(user_tag_name: String, user_ids: Vec<String>) -> CreateUserTagIntent {
        CreateUserTagIntent {
            user_tag_name,
            user_ids,
        }
    }
}

