/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePrivateKeyTagIntent {
    /// Human-readable name for a Private Key Tag.
    #[serde(rename = "privateKeyTagName")]
    pub private_key_tag_name: String,
    /// A list of Private Key IDs.
    #[serde(rename = "privateKeyIds")]
    pub private_key_ids: Vec<String>,
}

impl CreatePrivateKeyTagIntent {
    pub fn new(private_key_tag_name: String, private_key_ids: Vec<String>) -> CreatePrivateKeyTagIntent {
        CreatePrivateKeyTagIntent {
            private_key_tag_name,
            private_key_ids,
        }
    }
}

