/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrganizationIntent {
    /// Human-readable name for an Organization.
    #[serde(rename = "organizationName")]
    pub organization_name: String,
    /// The root user's email address.
    #[serde(rename = "rootEmail")]
    pub root_email: String,
    #[serde(rename = "rootAuthenticator")]
    pub root_authenticator: Box<models::AuthenticatorParams>,
    /// Unique identifier for the root user object.
    #[serde(rename = "rootUserId", skip_serializing_if = "Option::is_none")]
    pub root_user_id: Option<String>,
}

impl CreateOrganizationIntent {
    pub fn new(organization_name: String, root_email: String, root_authenticator: models::AuthenticatorParams) -> CreateOrganizationIntent {
        CreateOrganizationIntent {
            organization_name,
            root_email,
            root_authenticator: Box::new(root_authenticator),
            root_user_id: None,
        }
    }
}

