/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePrivateKeysIntent {
    /// A list of Private Keys.
    #[serde(rename = "privateKeys")]
    pub private_keys: Vec<models::PrivateKeyParams>,
}

impl CreatePrivateKeysIntent {
    pub fn new(private_keys: Vec<models::PrivateKeyParams>) -> CreatePrivateKeysIntent {
        CreatePrivateKeysIntent {
            private_keys,
        }
    }
}

