/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSubOrganizationIntent {
    /// Name for this sub-organization
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "rootAuthenticator")]
    pub root_authenticator: Box<models::AuthenticatorParamsV2>,
}

impl CreateSubOrganizationIntent {
    pub fn new(name: String, root_authenticator: models::AuthenticatorParamsV2) -> CreateSubOrganizationIntent {
        CreateSubOrganizationIntent {
            name,
            root_authenticator: Box::new(root_authenticator),
        }
    }
}

