/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKeysIntentV2 {
    /// A list of API Keys.
    #[serde(rename = "apiKeys")]
    pub api_keys: Vec<models::ApiKeyParamsV2>,
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl CreateApiKeysIntentV2 {
    pub fn new(api_keys: Vec<models::ApiKeyParamsV2>, user_id: String) -> CreateApiKeysIntentV2 {
        CreateApiKeysIntentV2 {
            api_keys,
            user_id,
        }
    }
}

