/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePolicyIntentV3 {
    /// Human-readable name for a Policy.
    #[serde(rename = "policyName")]
    pub policy_name: String,
    #[serde(rename = "effect")]
    pub effect: models::Effect,
    /// The condition expression that triggers the Effect
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    /// The consensus expression that triggers the Effect
    #[serde(rename = "consensus", skip_serializing_if = "Option::is_none")]
    pub consensus: Option<String>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl CreatePolicyIntentV3 {
    pub fn new(policy_name: String, effect: models::Effect) -> CreatePolicyIntentV3 {
        CreatePolicyIntentV3 {
            policy_name,
            effect,
            condition: None,
            consensus: None,
            notes: None,
        }
    }
}

