/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAuthenticatorsIntent {
    /// A list of Authenticators.
    #[serde(rename = "authenticators")]
    pub authenticators: Vec<models::AuthenticatorParams>,
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl CreateAuthenticatorsIntent {
    pub fn new(authenticators: Vec<models::AuthenticatorParams>, user_id: String) -> CreateAuthenticatorsIntent {
        CreateAuthenticatorsIntent {
            authenticators,
            user_id,
        }
    }
}

