/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePolicyIntentV2 {
    /// Human-readable name for a Policy.
    #[serde(rename = "policyName")]
    pub policy_name: String,
    /// A list of simple functions each including a subject, target and boolean. See Policy Engine Language section for additional details.
    #[serde(rename = "selectors")]
    pub selectors: Vec<models::SelectorV2>,
    #[serde(rename = "effect")]
    pub effect: models::Effect,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl CreatePolicyIntentV2 {
    pub fn new(policy_name: String, selectors: Vec<models::SelectorV2>, effect: models::Effect) -> CreatePolicyIntentV2 {
        CreatePolicyIntentV2 {
            policy_name,
            selectors,
            effect,
            notes: None,
        }
    }
}

