/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePoliciesIntent {
    /// An array of policy intents to be created.
    #[serde(rename = "policies")]
    pub policies: Vec<models::CreatePolicyIntentV3>,
}

impl CreatePoliciesIntent {
    pub fn new(policies: Vec<models::CreatePolicyIntentV3>) -> CreatePoliciesIntent {
        CreatePoliciesIntent {
            policies,
        }
    }
}

