/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSubOrganizationIntentV7 {
    /// Name for this sub-organization
    #[serde(rename = "subOrganizationName")]
    pub sub_organization_name: String,
    /// Root users to create within this sub-organization
    #[serde(rename = "rootUsers")]
    pub root_users: Vec<models::RootUserParamsV4>,
    /// The threshold of unique approvals to reach root quorum. This value must be less than or equal to the number of root users
    #[serde(rename = "rootQuorumThreshold")]
    pub root_quorum_threshold: i32,
    #[serde(rename = "wallet", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Box<models::WalletParams>>,
    /// Disable email recovery for the sub-organization
    #[serde(rename = "disableEmailRecovery", skip_serializing_if = "Option::is_none")]
    pub disable_email_recovery: Option<bool>,
    /// Disable email auth for the sub-organization
    #[serde(rename = "disableEmailAuth", skip_serializing_if = "Option::is_none")]
    pub disable_email_auth: Option<bool>,
    /// Disable OTP SMS auth for the sub-organization
    #[serde(rename = "disableSmsAuth", skip_serializing_if = "Option::is_none")]
    pub disable_sms_auth: Option<bool>,
    /// Disable OTP email auth for the sub-organization
    #[serde(rename = "disableOtpEmailAuth", skip_serializing_if = "Option::is_none")]
    pub disable_otp_email_auth: Option<bool>,
}

impl CreateSubOrganizationIntentV7 {
    pub fn new(sub_organization_name: String, root_users: Vec<models::RootUserParamsV4>, root_quorum_threshold: i32) -> CreateSubOrganizationIntentV7 {
        CreateSubOrganizationIntentV7 {
            sub_organization_name,
            root_users,
            root_quorum_threshold,
            wallet: None,
            disable_email_recovery: None,
            disable_email_auth: None,
            disable_sms_auth: None,
            disable_otp_email_auth: None,
        }
    }
}

