/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOauthProvidersIntent {
    /// The ID of the User to add an Oauth provider to
    #[serde(rename = "userId")]
    pub user_id: String,
    /// A list of Oauth providers.
    #[serde(rename = "oauthProviders")]
    pub oauth_providers: Vec<models::OauthProviderParams>,
}

impl CreateOauthProvidersIntent {
    pub fn new(user_id: String, oauth_providers: Vec<models::OauthProviderParams>) -> CreateOauthProvidersIntent {
        CreateOauthProvidersIntent {
            user_id,
            oauth_providers,
        }
    }
}

