/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWalletAccountsIntent {
    /// Unique identifier for a given Wallet.
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    /// A list of wallet Accounts.
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::WalletAccountParams>,
}

impl CreateWalletAccountsIntent {
    pub fn new(wallet_id: String, accounts: Vec<models::WalletAccountParams>) -> CreateWalletAccountsIntent {
        CreateWalletAccountsIntent {
            wallet_id,
            accounts,
        }
    }
}

