/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateReadWriteSessionIntent {
    /// Client-side public key generated by the user, to which the read write session bundle (credentials) will be encrypted.
    #[serde(rename = "targetPublicKey")]
    pub target_public_key: String,
    /// Email of the user to create a read write session for
    #[serde(rename = "email")]
    pub email: String,
    /// Optional human-readable name for an API Key. If none provided, default to Read Write Session - <Timestamp>
    #[serde(rename = "apiKeyName", skip_serializing_if = "Option::is_none")]
    pub api_key_name: Option<String>,
    /// Expiration window (in seconds) indicating how long the API key is valid. If not provided, a default of 15 minutes will be used.
    #[serde(rename = "expirationSeconds", skip_serializing_if = "Option::is_none")]
    pub expiration_seconds: Option<String>,
}

impl CreateReadWriteSessionIntent {
    pub fn new(target_public_key: String, email: String) -> CreateReadWriteSessionIntent {
        CreateReadWriteSessionIntent {
            target_public_key,
            email,
            api_key_name: None,
            expiration_seconds: None,
        }
    }
}

