/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiOnlyUsersIntent {
    /// A list of API-only Users to create.
    #[serde(rename = "apiOnlyUsers")]
    pub api_only_users: Vec<models::ApiOnlyUserParams>,
}

impl CreateApiOnlyUsersIntent {
    pub fn new(api_only_users: Vec<models::ApiOnlyUserParams>) -> CreateApiOnlyUsersIntent {
        CreateApiOnlyUsersIntent {
            api_only_users,
        }
    }
}

