/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSubOrganizationIntentV2 {
    /// Name for this sub-organization
    #[serde(rename = "subOrganizationName")]
    pub sub_organization_name: String,
    /// Root users to create within this sub-organization
    #[serde(rename = "rootUsers")]
    pub root_users: Vec<models::RootUserParams>,
    /// The threshold of unique approvals to reach root quorum. This value must be less than or equal to the number of root users
    #[serde(rename = "rootQuorumThreshold")]
    pub root_quorum_threshold: i32,
}

impl CreateSubOrganizationIntentV2 {
    pub fn new(sub_organization_name: String, root_users: Vec<models::RootUserParams>, root_quorum_threshold: i32) -> CreateSubOrganizationIntentV2 {
        CreateSubOrganizationIntentV2 {
            sub_organization_name,
            root_users,
            root_quorum_threshold,
        }
    }
}

