/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUsersIntent {
    /// A list of Users.
    #[serde(rename = "users")]
    pub users: Vec<models::UserParams>,
}

impl CreateUsersIntent {
    pub fn new(users: Vec<models::UserParams>) -> CreateUsersIntent {
        CreateUsersIntent {
            users,
        }
    }
}

