/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CredentialType {
    #[serde(rename = "CREDENTIAL_TYPE_WEBAUTHN_AUTHENTICATOR")]
    CredentialTypeWebauthnAuthenticator,
    #[serde(rename = "CREDENTIAL_TYPE_API_KEY_P256")]
    CredentialTypeApiKeyP256,
    #[serde(rename = "CREDENTIAL_TYPE_RECOVER_USER_KEY_P256")]
    CredentialTypeRecoverUserKeyP256,
    #[serde(rename = "CREDENTIAL_TYPE_API_KEY_SECP256K1")]
    CredentialTypeApiKeySecp256K1,
    #[serde(rename = "CREDENTIAL_TYPE_EMAIL_AUTH_KEY_P256")]
    CredentialTypeEmailAuthKeyP256,
    #[serde(rename = "CREDENTIAL_TYPE_API_KEY_ED25519")]
    CredentialTypeApiKeyEd25519,
    #[serde(rename = "CREDENTIAL_TYPE_OTP_AUTH_KEY_P256")]
    CredentialTypeOtpAuthKeyP256,

}

impl std::fmt::Display for CredentialType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CredentialTypeWebauthnAuthenticator => write!(f, "CREDENTIAL_TYPE_WEBAUTHN_AUTHENTICATOR"),
            Self::CredentialTypeApiKeyP256 => write!(f, "CREDENTIAL_TYPE_API_KEY_P256"),
            Self::CredentialTypeRecoverUserKeyP256 => write!(f, "CREDENTIAL_TYPE_RECOVER_USER_KEY_P256"),
            Self::CredentialTypeApiKeySecp256K1 => write!(f, "CREDENTIAL_TYPE_API_KEY_SECP256K1"),
            Self::CredentialTypeEmailAuthKeyP256 => write!(f, "CREDENTIAL_TYPE_EMAIL_AUTH_KEY_P256"),
            Self::CredentialTypeApiKeyEd25519 => write!(f, "CREDENTIAL_TYPE_API_KEY_ED25519"),
            Self::CredentialTypeOtpAuthKeyP256 => write!(f, "CREDENTIAL_TYPE_OTP_AUTH_KEY_P256"),
        }
    }
}

impl Default for CredentialType {
    fn default() -> CredentialType {
        Self::CredentialTypeWebauthnAuthenticator
    }
}

