/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Curve {
    #[serde(rename = "CURVE_SECP256K1")]
    CurveSecp256K1,
    #[serde(rename = "CURVE_ED25519")]
    CurveEd25519,

}

impl std::fmt::Display for Curve {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CurveSecp256K1 => write!(f, "CURVE_SECP256K1"),
            Self::CurveEd25519 => write!(f, "CURVE_ED25519"),
        }
    }
}

impl Default for Curve {
    fn default() -> Curve {
        Self::CurveSecp256K1
    }
}

