/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteSubOrganizationIntent {
    /// Sub-organization deletion, by default, requires associated wallets and private keys to be exported for security reasons. Set this boolean to true to force sub-organization deletion even if some wallets or private keys within it have not been exported yet. Default: false.
    #[serde(rename = "deleteWithoutExport", skip_serializing_if = "Option::is_none")]
    pub delete_without_export: Option<bool>,
}

impl DeleteSubOrganizationIntent {
    pub fn new() -> DeleteSubOrganizationIntent {
        DeleteSubOrganizationIntent {
            delete_without_export: None,
        }
    }
}

