/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteInvitationIntent {
    /// Unique identifier for a given Invitation object.
    #[serde(rename = "invitationId")]
    pub invitation_id: String,
}

impl DeleteInvitationIntent {
    pub fn new(invitation_id: String) -> DeleteInvitationIntent {
        DeleteInvitationIntent {
            invitation_id,
        }
    }
}

