/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeletePrivateKeysIntent {
    /// List of unique identifiers for private keys within an organization
    #[serde(rename = "privateKeyIds")]
    pub private_key_ids: Vec<String>,
    /// Optional parameter for deleting the private keys, even if any have not been previously exported. If they have been exported, this field is ignored.
    #[serde(rename = "deleteWithoutExport", skip_serializing_if = "Option::is_none")]
    pub delete_without_export: Option<bool>,
}

impl DeletePrivateKeysIntent {
    pub fn new(private_key_ids: Vec<String>) -> DeletePrivateKeysIntent {
        DeletePrivateKeysIntent {
            private_key_ids,
            delete_without_export: None,
        }
    }
}

