/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeletePrivateKeyTagsIntent {
    /// A list of Private Key Tag IDs.
    #[serde(rename = "privateKeyTagIds")]
    pub private_key_tag_ids: Vec<String>,
}

impl DeletePrivateKeyTagsIntent {
    pub fn new(private_key_tag_ids: Vec<String>) -> DeletePrivateKeyTagsIntent {
        DeletePrivateKeyTagsIntent {
            private_key_tag_ids,
        }
    }
}

