/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteUsersIntent {
    /// A list of User IDs.
    #[serde(rename = "userIds")]
    pub user_ids: Vec<String>,
}

impl DeleteUsersIntent {
    pub fn new(user_ids: Vec<String>) -> DeleteUsersIntent {
        DeleteUsersIntent {
            user_ids,
        }
    }
}

