/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteUserTagsIntent {
    /// A list of User Tag IDs.
    #[serde(rename = "userTagIds")]
    pub user_tag_ids: Vec<String>,
}

impl DeleteUserTagsIntent {
    pub fn new(user_tag_ids: Vec<String>) -> DeleteUserTagsIntent {
        DeleteUserTagsIntent {
            user_tag_ids,
        }
    }
}

