/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteOauthProvidersIntent {
    /// The ID of the User to remove an Oauth provider from
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Unique identifier for a given Provider.
    #[serde(rename = "providerIds")]
    pub provider_ids: Vec<String>,
}

impl DeleteOauthProvidersIntent {
    pub fn new(user_id: String, provider_ids: Vec<String>) -> DeleteOauthProvidersIntent {
        DeleteOauthProvidersIntent {
            user_id,
            provider_ids,
        }
    }
}

