/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteAuthenticatorsIntent {
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// A list of Authenticator IDs.
    #[serde(rename = "authenticatorIds")]
    pub authenticator_ids: Vec<String>,
}

impl DeleteAuthenticatorsIntent {
    pub fn new(user_id: String, authenticator_ids: Vec<String>) -> DeleteAuthenticatorsIntent {
        DeleteAuthenticatorsIntent {
            user_id,
            authenticator_ids,
        }
    }
}

