/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteWalletsIntent {
    /// List of unique identifiers for wallets within an organization
    #[serde(rename = "walletIds")]
    pub wallet_ids: Vec<String>,
    /// Optional parameter for deleting the wallets, even if any have not been previously exported. If they have been exported, this field is ignored.
    #[serde(rename = "deleteWithoutExport", skip_serializing_if = "Option::is_none")]
    pub delete_without_export: Option<bool>,
}

impl DeleteWalletsIntent {
    pub fn new(wallet_ids: Vec<String>) -> DeleteWalletsIntent {
        DeleteWalletsIntent {
            wallet_ids,
            delete_without_export: None,
        }
    }
}

