/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeletePolicyIntent {
    /// Unique identifier for a given Policy.
    #[serde(rename = "policyId")]
    pub policy_id: String,
}

impl DeletePolicyIntent {
    pub fn new(policy_id: String) -> DeletePolicyIntent {
        DeletePolicyIntent {
            policy_id,
        }
    }
}

