/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteApiKeysIntent {
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// A list of API Key IDs.
    #[serde(rename = "apiKeyIds")]
    pub api_key_ids: Vec<String>,
}

impl DeleteApiKeysIntent {
    pub fn new(user_id: String, api_key_ids: Vec<String>) -> DeleteApiKeysIntent {
        DeleteApiKeysIntent {
            user_id,
            api_key_ids,
        }
    }
}

