/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeletePaymentMethodIntent {
    /// The payment method that the customer wants to remove.
    #[serde(rename = "paymentMethodId")]
    pub payment_method_id: String,
}

impl DeletePaymentMethodIntent {
    pub fn new(payment_method_id: String) -> DeletePaymentMethodIntent {
        DeletePaymentMethodIntent {
            payment_method_id,
        }
    }
}

