/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisablePrivateKeyIntent {
    /// Unique identifier for a given Private Key.
    #[serde(rename = "privateKeyId")]
    pub private_key_id: String,
}

impl DisablePrivateKeyIntent {
    pub fn new(private_key_id: String) -> DisablePrivateKeyIntent {
        DisablePrivateKeyIntent {
            private_key_id,
        }
    }
}

