/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Effect {
    #[serde(rename = "EFFECT_ALLOW")]
    EffectAllow,
    #[serde(rename = "EFFECT_DENY")]
    EffectDeny,

}

impl std::fmt::Display for Effect {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::EffectAllow => write!(f, "EFFECT_ALLOW"),
            Self::EffectDeny => write!(f, "EFFECT_DENY"),
        }
    }
}

impl Default for Effect {
    fn default() -> Effect {
        Self::EffectAllow
    }
}

