/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailAuthIntentV2 {
    /// Email of the authenticating user.
    #[serde(rename = "email")]
    pub email: String,
    /// Client-side public key generated by the user, to which the email auth bundle (credentials) will be encrypted.
    #[serde(rename = "targetPublicKey")]
    pub target_public_key: String,
    /// Optional human-readable name for an API Key. If none provided, default to Email Auth - <Timestamp>
    #[serde(rename = "apiKeyName", skip_serializing_if = "Option::is_none")]
    pub api_key_name: Option<String>,
    /// Expiration window (in seconds) indicating how long the API key is valid. If not provided, a default of 15 minutes will be used.
    #[serde(rename = "expirationSeconds", skip_serializing_if = "Option::is_none")]
    pub expiration_seconds: Option<String>,
    #[serde(rename = "emailCustomization", skip_serializing_if = "Option::is_none")]
    pub email_customization: Option<Box<models::EmailCustomizationParams>>,
    /// Invalidate all other previously generated Email Auth API keys
    #[serde(rename = "invalidateExisting", skip_serializing_if = "Option::is_none")]
    pub invalidate_existing: Option<bool>,
    /// Optional custom email address from which to send the email
    #[serde(rename = "sendFromEmailAddress", skip_serializing_if = "Option::is_none")]
    pub send_from_email_address: Option<String>,
}

impl EmailAuthIntentV2 {
    pub fn new(email: String, target_public_key: String) -> EmailAuthIntentV2 {
        EmailAuthIntentV2 {
            email,
            target_public_key,
            api_key_name: None,
            expiration_seconds: None,
            email_customization: None,
            invalidate_existing: None,
            send_from_email_address: None,
        }
    }
}

