/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailCustomizationParams {
    /// The name of the application.
    #[serde(rename = "appName", skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    /// A URL pointing to a logo in PNG format. Note this logo will be resized to fit into 340px x 124px.
    #[serde(rename = "logoUrl", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<String>,
    /// A template for the URL to be used in a magic link button, e.g. `https://dapp.xyz/%s`. The auth bundle will be interpolated into the `%s`.
    #[serde(rename = "magicLinkTemplate", skip_serializing_if = "Option::is_none")]
    pub magic_link_template: Option<String>,
    /// JSON object containing key/value pairs to be used with custom templates.
    #[serde(rename = "templateVariables", skip_serializing_if = "Option::is_none")]
    pub template_variables: Option<String>,
    /// Unique identifier for a given Email Template. If not specified, the default is the most recent Email Template.
    #[serde(rename = "templateId", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<String>,
}

impl EmailCustomizationParams {
    pub fn new() -> EmailCustomizationParams {
        EmailCustomizationParams {
            app_name: None,
            logo_url: None,
            magic_link_template: None,
            template_variables: None,
            template_id: None,
        }
    }
}

