/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportPrivateKeyIntent {
    /// Unique identifier for a given Private Key.
    #[serde(rename = "privateKeyId")]
    pub private_key_id: String,
    /// Client-side public key generated by the user, to which the export bundle will be encrypted.
    #[serde(rename = "targetPublicKey")]
    pub target_public_key: String,
}

impl ExportPrivateKeyIntent {
    pub fn new(private_key_id: String, target_public_key: String) -> ExportPrivateKeyIntent {
        ExportPrivateKeyIntent {
            private_key_id,
            target_public_key,
        }
    }
}

