/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportWalletIntent {
    /// Unique identifier for a given Wallet.
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    /// Client-side public key generated by the user, to which the export bundle will be encrypted.
    #[serde(rename = "targetPublicKey")]
    pub target_public_key: String,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<models::MnemonicLanguage>,
}

impl ExportWalletIntent {
    pub fn new(wallet_id: String, target_public_key: String) -> ExportWalletIntent {
        ExportWalletIntent {
            wallet_id,
            target_public_key,
            language: None,
        }
    }
}

