/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportWalletAccountIntent {
    /// Address to identify Wallet Account.
    #[serde(rename = "address")]
    pub address: String,
    /// Client-side public key generated by the user, to which the export bundle will be encrypted.
    #[serde(rename = "targetPublicKey")]
    pub target_public_key: String,
}

impl ExportWalletAccountIntent {
    pub fn new(address: String, target_public_key: String) -> ExportWalletAccountIntent {
        ExportWalletAccountIntent {
            address,
            target_public_key,
        }
    }
}

