/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalPeriodDataPeriodV1PeriodTimestamp {
    #[serde(rename = "seconds")]
    pub seconds: String,
    #[serde(rename = "nanos")]
    pub nanos: String,
}

impl ExternalPeriodDataPeriodV1PeriodTimestamp {
    pub fn new(seconds: String, nanos: String) -> ExternalPeriodDataPeriodV1PeriodTimestamp {
        ExternalPeriodDataPeriodV1PeriodTimestamp {
            seconds,
            nanos,
        }
    }
}

