/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalPeriodDataPeriodV1PeriodQuorum {
    /// Count of unique approvals required to meet quorum.
    #[serde(rename = "threshold")]
    pub threshold: i32,
    /// Unique identifiers of quorum set members.
    #[serde(rename = "userIds")]
    pub user_ids: Vec<String>,
}

impl ExternalPeriodDataPeriodV1PeriodQuorum {
    pub fn new(threshold: i32, user_ids: Vec<String>) -> ExternalPeriodDataPeriodV1PeriodQuorum {
        ExternalPeriodDataPeriodV1PeriodQuorum {
            threshold,
            user_ids,
        }
    }
}

