/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalPeriodDataPeriodV1PeriodCredential {
    /// The public component of a cryptographic key pair used to sign messages and transactions.
    #[serde(rename = "publicKey")]
    pub public_key: String,
    #[serde(rename = "type")]
    pub r#type: models::CredentialType,
}

impl ExternalPeriodDataPeriodV1PeriodCredential {
    pub fn new(public_key: String, r#type: models::CredentialType) -> ExternalPeriodDataPeriodV1PeriodCredential {
        ExternalPeriodDataPeriodV1PeriodCredential {
            public_key,
            r#type,
        }
    }
}

