/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Feature {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<models::FeatureName>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl Feature {
    pub fn new() -> Feature {
        Feature {
            name: None,
            value: None,
        }
    }
}

