/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeatureName {
    #[serde(rename = "FEATURE_NAME_ROOT_USER_EMAIL_RECOVERY")]
    FeatureNameRootUserEmailRecovery,
    #[serde(rename = "FEATURE_NAME_WEBAUTHN_ORIGINS")]
    FeatureNameWebauthnOrigins,
    #[serde(rename = "FEATURE_NAME_EMAIL_AUTH")]
    FeatureNameEmailAuth,
    #[serde(rename = "FEATURE_NAME_EMAIL_RECOVERY")]
    FeatureNameEmailRecovery,
    #[serde(rename = "FEATURE_NAME_WEBHOOK")]
    FeatureNameWebhook,
    #[serde(rename = "FEATURE_NAME_SMS_AUTH")]
    FeatureNameSmsAuth,
    #[serde(rename = "FEATURE_NAME_OTP_EMAIL_AUTH")]
    FeatureNameOtpEmailAuth,

}

impl std::fmt::Display for FeatureName {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FeatureNameRootUserEmailRecovery => write!(f, "FEATURE_NAME_ROOT_USER_EMAIL_RECOVERY"),
            Self::FeatureNameWebauthnOrigins => write!(f, "FEATURE_NAME_WEBAUTHN_ORIGINS"),
            Self::FeatureNameEmailAuth => write!(f, "FEATURE_NAME_EMAIL_AUTH"),
            Self::FeatureNameEmailRecovery => write!(f, "FEATURE_NAME_EMAIL_RECOVERY"),
            Self::FeatureNameWebhook => write!(f, "FEATURE_NAME_WEBHOOK"),
            Self::FeatureNameSmsAuth => write!(f, "FEATURE_NAME_SMS_AUTH"),
            Self::FeatureNameOtpEmailAuth => write!(f, "FEATURE_NAME_OTP_EMAIL_AUTH"),
        }
    }
}

impl Default for FeatureName {
    fn default() -> FeatureName {
        Self::FeatureNameRootUserEmailRecovery
    }
}

