/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAuthenticatorRequest {
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Unique identifier for a given Authenticator.
    #[serde(rename = "authenticatorId")]
    pub authenticator_id: String,
}

impl GetAuthenticatorRequest {
    pub fn new(organization_id: String, authenticator_id: String) -> GetAuthenticatorRequest {
        GetAuthenticatorRequest {
            organization_id,
            authenticator_id,
        }
    }
}

