/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWalletAccountsResponse {
    /// A list of Accounts generated from a Wallet that share a common seed
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::WalletAccount>,
}

impl GetWalletAccountsResponse {
    pub fn new(accounts: Vec<models::WalletAccount>) -> GetWalletAccountsResponse {
        GetWalletAccountsResponse {
            accounts,
        }
    }
}

