/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPolicyRequest {
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Unique identifier for a given Policy.
    #[serde(rename = "policyId")]
    pub policy_id: String,
}

impl GetPolicyRequest {
    pub fn new(organization_id: String, policy_id: String) -> GetPolicyRequest {
        GetPolicyRequest {
            organization_id,
            policy_id,
        }
    }
}

