/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPrivateKeyRequest {
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Unique identifier for a given Private Key.
    #[serde(rename = "privateKeyId")]
    pub private_key_id: String,
}

impl GetPrivateKeyRequest {
    pub fn new(organization_id: String, private_key_id: String) -> GetPrivateKeyRequest {
        GetPrivateKeyRequest {
            organization_id,
            private_key_id,
        }
    }
}

