/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetActivitiesResponse {
    /// A list of Activities.
    #[serde(rename = "activities")]
    pub activities: Vec<models::Activity>,
}

impl GetActivitiesResponse {
    pub fn new(activities: Vec<models::Activity>) -> GetActivitiesResponse {
        GetActivitiesResponse {
            activities,
        }
    }
}

