/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWhoamiResponse {
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Human-readable name for an Organization.
    #[serde(rename = "organizationName")]
    pub organization_name: String,
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Human-readable name for a User.
    #[serde(rename = "username")]
    pub username: String,
}

impl GetWhoamiResponse {
    pub fn new(organization_id: String, organization_name: String, user_id: String, username: String) -> GetWhoamiResponse {
        GetWhoamiResponse {
            organization_id,
            organization_name,
            user_id,
            username,
        }
    }
}

