/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWalletResponse {
    #[serde(rename = "wallet")]
    pub wallet: Box<models::Wallet>,
}

impl GetWalletResponse {
    pub fn new(wallet: models::Wallet) -> GetWalletResponse {
        GetWalletResponse {
            wallet: Box::new(wallet),
        }
    }
}

