/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPrivateKeyResponse {
    #[serde(rename = "privateKey")]
    pub private_key: Box<models::PrivateKey>,
}

impl GetPrivateKeyResponse {
    pub fn new(private_key: models::PrivateKey) -> GetPrivateKeyResponse {
        GetPrivateKeyResponse {
            private_key: Box::new(private_key),
        }
    }
}

