/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetActivityRequest {
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Unique identifier for a given Activity object.
    #[serde(rename = "activityId")]
    pub activity_id: String,
}

impl GetActivityRequest {
    pub fn new(organization_id: String, activity_id: String) -> GetActivityRequest {
        GetActivityRequest {
            organization_id,
            activity_id,
        }
    }
}

