/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWhoamiRequest {
    /// Unique identifier for a given Organization. If the request is being made by a WebAuthN user and their Sub-Organization ID is unknown, this can be the Parent Organization ID; using the Sub-Organization ID when possible is preferred due to performance reasons.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
}

impl GetWhoamiRequest {
    pub fn new(organization_id: String) -> GetWhoamiRequest {
        GetWhoamiRequest {
            organization_id,
        }
    }
}

