/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWalletsResponse {
    /// A list of Wallets.
    #[serde(rename = "wallets")]
    pub wallets: Vec<models::Wallet>,
}

impl GetWalletsResponse {
    pub fn new(wallets: Vec<models::Wallet>) -> GetWalletsResponse {
        GetWalletsResponse {
            wallets,
        }
    }
}

