/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAuthenticatorsRequest {
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl GetAuthenticatorsRequest {
    pub fn new(organization_id: String, user_id: String) -> GetAuthenticatorsRequest {
        GetAuthenticatorsRequest {
            organization_id,
            user_id,
        }
    }
}

