/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSubOrgIdsRequest {
    /// Unique identifier for the parent Organization. This is used to find sub-organizations within it.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Specifies the type of filter to apply, i.e 'CREDENTIAL_ID', 'NAME', 'USERNAME', 'EMAIL', 'PHONE_NUMBER', 'OIDC_TOKEN' or 'PUBLIC_KEY'
    #[serde(rename = "filterType", skip_serializing_if = "Option::is_none")]
    pub filter_type: Option<String>,
    /// The value of the filter to apply for the specified type. For example, a specific email or name string.
    #[serde(rename = "filterValue", skip_serializing_if = "Option::is_none")]
    pub filter_value: Option<String>,
    #[serde(rename = "paginationOptions", skip_serializing_if = "Option::is_none")]
    pub pagination_options: Option<Box<models::Pagination>>,
}

impl GetSubOrgIdsRequest {
    pub fn new(organization_id: String) -> GetSubOrgIdsRequest {
        GetSubOrgIdsRequest {
            organization_id,
            filter_type: None,
            filter_value: None,
            pagination_options: None,
        }
    }
}

