/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizationConfigsResponse {
    #[serde(rename = "configs")]
    pub configs: Box<models::Config>,
}

impl GetOrganizationConfigsResponse {
    pub fn new(configs: models::Config) -> GetOrganizationConfigsResponse {
        GetOrganizationConfigsResponse {
            configs: Box::new(configs),
        }
    }
}

