/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApiKeysRequest {
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Unique identifier for a given User.
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl GetApiKeysRequest {
    pub fn new(organization_id: String) -> GetApiKeysRequest {
        GetApiKeysRequest {
            organization_id,
            user_id: None,
        }
    }
}

