/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWalletAccountsRequest {
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Unique identifier for a given Wallet.
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "paginationOptions", skip_serializing_if = "Option::is_none")]
    pub pagination_options: Option<Box<models::Pagination>>,
}

impl GetWalletAccountsRequest {
    pub fn new(organization_id: String, wallet_id: String) -> GetWalletAccountsRequest {
        GetWalletAccountsRequest {
            organization_id,
            wallet_id,
            pagination_options: None,
        }
    }
}

