/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApiKeysResponse {
    /// A list of API keys.
    #[serde(rename = "apiKeys")]
    pub api_keys: Vec<models::ApiKey>,
}

impl GetApiKeysResponse {
    pub fn new(api_keys: Vec<models::ApiKey>) -> GetApiKeysResponse {
        GetApiKeysResponse {
            api_keys,
        }
    }
}

