/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApiKeyResponse {
    #[serde(rename = "apiKey")]
    pub api_key: Box<models::ApiKey>,
}

impl GetApiKeyResponse {
    pub fn new(api_key: models::ApiKey) -> GetApiKeyResponse {
        GetApiKeyResponse {
            api_key: Box::new(api_key),
        }
    }
}

