/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPolicyResponse {
    #[serde(rename = "policy")]
    pub policy: Box<models::Policy>,
}

impl GetPolicyResponse {
    pub fn new(policy: models::Policy) -> GetPolicyResponse {
        GetPolicyResponse {
            policy: Box::new(policy),
        }
    }
}

