/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOauthProvidersResponse {
    /// A list of Oauth Providers
    #[serde(rename = "oauthProviders")]
    pub oauth_providers: Vec<models::OauthProvider>,
}

impl GetOauthProvidersResponse {
    pub fn new(oauth_providers: Vec<models::OauthProvider>) -> GetOauthProvidersResponse {
        GetOauthProvidersResponse {
            oauth_providers,
        }
    }
}

