/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAuthenticatorResponse {
    #[serde(rename = "authenticator")]
    pub authenticator: Box<models::Authenticator>,
}

impl GetAuthenticatorResponse {
    pub fn new(authenticator: models::Authenticator) -> GetAuthenticatorResponse {
        GetAuthenticatorResponse {
            authenticator: Box::new(authenticator),
        }
    }
}

