/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVerifiedSubOrgIdsRequest {
    /// Unique identifier for the parent Organization. This is used to find sub-organizations within it.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Specifies the type of filter to apply, i.e 'EMAIL', 'PHONE_NUMBER'
    #[serde(rename = "filterType", skip_serializing_if = "Option::is_none")]
    pub filter_type: Option<String>,
    /// The value of the filter to apply for the specified type. For example, a specific email or phone number string.
    #[serde(rename = "filterValue", skip_serializing_if = "Option::is_none")]
    pub filter_value: Option<String>,
    #[serde(rename = "paginationOptions", skip_serializing_if = "Option::is_none")]
    pub pagination_options: Option<Box<models::Pagination>>,
}

impl GetVerifiedSubOrgIdsRequest {
    pub fn new(organization_id: String) -> GetVerifiedSubOrgIdsRequest {
        GetVerifiedSubOrgIdsRequest {
            organization_id,
            filter_type: None,
            filter_value: None,
            pagination_options: None,
        }
    }
}

