/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAuthenticatorsResponse {
    /// A list of authenticators.
    #[serde(rename = "authenticators")]
    pub authenticators: Vec<models::Authenticator>,
}

impl GetAuthenticatorsResponse {
    pub fn new(authenticators: Vec<models::Authenticator>) -> GetAuthenticatorsResponse {
        GetAuthenticatorsResponse {
            authenticators,
        }
    }
}

