/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApiKeyRequest {
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Unique identifier for a given API key.
    #[serde(rename = "apiKeyId")]
    pub api_key_id: String,
}

impl GetApiKeyRequest {
    pub fn new(organization_id: String, api_key_id: String) -> GetApiKeyRequest {
        GetApiKeyRequest {
            organization_id,
            api_key_id,
        }
    }
}

