/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSubOrgIdsResponse {
    /// List of unique identifiers for the matching sub-organizations.
    #[serde(rename = "organizationIds")]
    pub organization_ids: Vec<String>,
}

impl GetSubOrgIdsResponse {
    pub fn new(organization_ids: Vec<String>) -> GetSubOrgIdsResponse {
        GetSubOrgIdsResponse {
            organization_ids,
        }
    }
}

