/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetActivitiesRequest {
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// Array of Activity Statuses filtering which Activities will be listed in the response.
    #[serde(rename = "filterByStatus", skip_serializing_if = "Option::is_none")]
    pub filter_by_status: Option<Vec<models::ActivityStatus>>,
    #[serde(rename = "paginationOptions", skip_serializing_if = "Option::is_none")]
    pub pagination_options: Option<Box<models::Pagination>>,
    /// Array of Activity Types filtering which Activities will be listed in the response.
    #[serde(rename = "filterByType", skip_serializing_if = "Option::is_none")]
    pub filter_by_type: Option<Vec<models::ActivityType>>,
}

impl GetActivitiesRequest {
    pub fn new(organization_id: String) -> GetActivitiesRequest {
        GetActivitiesRequest {
            organization_id,
            filter_by_status: None,
            pagination_options: None,
            filter_by_type: None,
        }
    }
}

