/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPoliciesResponse {
    /// A list of Policies.
    #[serde(rename = "policies")]
    pub policies: Vec<models::Policy>,
}

impl GetPoliciesResponse {
    pub fn new(policies: Vec<models::Policy>) -> GetPoliciesResponse {
        GetPoliciesResponse {
            policies,
        }
    }
}

