/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HashFunction {
    #[serde(rename = "HASH_FUNCTION_NO_OP")]
    HashFunctionNoOp,
    #[serde(rename = "HASH_FUNCTION_SHA256")]
    HashFunctionSha256,
    #[serde(rename = "HASH_FUNCTION_KECCAK256")]
    HashFunctionKeccak256,
    #[serde(rename = "HASH_FUNCTION_NOT_APPLICABLE")]
    HashFunctionNotApplicable,

}

impl std::fmt::Display for HashFunction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::HashFunctionNoOp => write!(f, "HASH_FUNCTION_NO_OP"),
            Self::HashFunctionSha256 => write!(f, "HASH_FUNCTION_SHA256"),
            Self::HashFunctionKeccak256 => write!(f, "HASH_FUNCTION_KECCAK256"),
            Self::HashFunctionNotApplicable => write!(f, "HASH_FUNCTION_NOT_APPLICABLE"),
        }
    }
}

impl Default for HashFunction {
    fn default() -> HashFunction {
        Self::HashFunctionNoOp
    }
}

