/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportWalletIntent {
    /// The ID of the User importing a Wallet.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Human-readable name for a Wallet.
    #[serde(rename = "walletName")]
    pub wallet_name: String,
    /// Bundle containing a wallet mnemonic encrypted to the enclave's target public key.
    #[serde(rename = "encryptedBundle")]
    pub encrypted_bundle: String,
    /// A list of wallet Accounts.
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::WalletAccountParams>,
}

impl ImportWalletIntent {
    pub fn new(user_id: String, wallet_name: String, encrypted_bundle: String, accounts: Vec<models::WalletAccountParams>) -> ImportWalletIntent {
        ImportWalletIntent {
            user_id,
            wallet_name,
            encrypted_bundle,
            accounts,
        }
    }
}

