/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportPrivateKeyIntent {
    /// The ID of the User importing a Private Key.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Human-readable name for a Private Key.
    #[serde(rename = "privateKeyName")]
    pub private_key_name: String,
    /// Bundle containing a raw private key encrypted to the enclave's target public key.
    #[serde(rename = "encryptedBundle")]
    pub encrypted_bundle: String,
    #[serde(rename = "curve")]
    pub curve: models::Curve,
    /// Cryptocurrency-specific formats for a derived address (e.g., Ethereum).
    #[serde(rename = "addressFormats")]
    pub address_formats: Vec<models::AddressFormat>,
}

impl ImportPrivateKeyIntent {
    pub fn new(user_id: String, private_key_name: String, encrypted_bundle: String, curve: models::Curve, address_formats: Vec<models::AddressFormat>) -> ImportPrivateKeyIntent {
        ImportPrivateKeyIntent {
            user_id,
            private_key_name,
            encrypted_bundle,
            curve,
            address_formats,
        }
    }
}

