/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InitImportPrivateKeyIntent {
    /// The ID of the User importing a Private Key.
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl InitImportPrivateKeyIntent {
    pub fn new(user_id: String) -> InitImportPrivateKeyIntent {
        InitImportPrivateKeyIntent {
            user_id,
        }
    }
}

