/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InitUserEmailRecoveryIntent {
    /// Email of the user starting recovery
    #[serde(rename = "email")]
    pub email: String,
    /// Client-side public key generated by the user, to which the recovery bundle will be encrypted.
    #[serde(rename = "targetPublicKey")]
    pub target_public_key: String,
    /// Expiration window (in seconds) indicating how long the recovery credential is valid. If not provided, a default of 15 minutes will be used.
    #[serde(rename = "expirationSeconds", skip_serializing_if = "Option::is_none")]
    pub expiration_seconds: Option<String>,
    #[serde(rename = "emailCustomization", skip_serializing_if = "Option::is_none")]
    pub email_customization: Option<Box<models::EmailCustomizationParams>>,
}

impl InitUserEmailRecoveryIntent {
    pub fn new(email: String, target_public_key: String) -> InitUserEmailRecoveryIntent {
        InitUserEmailRecoveryIntent {
            email,
            target_public_key,
            expiration_seconds: None,
            email_customization: None,
        }
    }
}

