/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InitOtpAuthIntent {
    /// Enum to specifiy whether to send OTP via SMS or email
    #[serde(rename = "otpType")]
    pub otp_type: String,
    /// Email or phone number to send the OTP code to
    #[serde(rename = "contact")]
    pub contact: String,
    #[serde(rename = "emailCustomization", skip_serializing_if = "Option::is_none")]
    pub email_customization: Option<Box<models::EmailCustomizationParams>>,
    #[serde(rename = "smsCustomization", skip_serializing_if = "Option::is_none")]
    pub sms_customization: Option<Box<models::SmsCustomizationParams>>,
    /// Optional client-generated user identifier to enable per-user rate limiting for SMS auth. We recommend using a hash of the client-side IP address.
    #[serde(rename = "userIdentifier", skip_serializing_if = "Option::is_none")]
    pub user_identifier: Option<String>,
    /// Optional custom email address from which to send the OTP email
    #[serde(rename = "sendFromEmailAddress", skip_serializing_if = "Option::is_none")]
    pub send_from_email_address: Option<String>,
}

impl InitOtpAuthIntent {
    pub fn new(otp_type: String, contact: String) -> InitOtpAuthIntent {
        InitOtpAuthIntent {
            otp_type,
            contact,
            email_customization: None,
            sms_customization: None,
            user_identifier: None,
            send_from_email_address: None,
        }
    }
}

