/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Intent {
    #[serde(rename = "createOrganizationIntent", skip_serializing_if = "Option::is_none")]
    pub create_organization_intent: Option<Box<models::CreateOrganizationIntent>>,
    #[serde(rename = "createAuthenticatorsIntent", skip_serializing_if = "Option::is_none")]
    pub create_authenticators_intent: Option<Box<models::CreateAuthenticatorsIntent>>,
    #[serde(rename = "createUsersIntent", skip_serializing_if = "Option::is_none")]
    pub create_users_intent: Option<Box<models::CreateUsersIntent>>,
    #[serde(rename = "createPrivateKeysIntent", skip_serializing_if = "Option::is_none")]
    pub create_private_keys_intent: Option<Box<models::CreatePrivateKeysIntent>>,
    #[serde(rename = "signRawPayloadIntent", skip_serializing_if = "Option::is_none")]
    pub sign_raw_payload_intent: Option<Box<models::SignRawPayloadIntent>>,
    #[serde(rename = "createInvitationsIntent", skip_serializing_if = "Option::is_none")]
    pub create_invitations_intent: Option<Box<models::CreateInvitationsIntent>>,
    #[serde(rename = "acceptInvitationIntent", skip_serializing_if = "Option::is_none")]
    pub accept_invitation_intent: Option<Box<models::AcceptInvitationIntent>>,
    #[serde(rename = "createPolicyIntent", skip_serializing_if = "Option::is_none")]
    pub create_policy_intent: Option<Box<models::CreatePolicyIntent>>,
    #[serde(rename = "disablePrivateKeyIntent", skip_serializing_if = "Option::is_none")]
    pub disable_private_key_intent: Option<Box<models::DisablePrivateKeyIntent>>,
    #[serde(rename = "deleteUsersIntent", skip_serializing_if = "Option::is_none")]
    pub delete_users_intent: Option<Box<models::DeleteUsersIntent>>,
    #[serde(rename = "deleteAuthenticatorsIntent", skip_serializing_if = "Option::is_none")]
    pub delete_authenticators_intent: Option<Box<models::DeleteAuthenticatorsIntent>>,
    #[serde(rename = "deleteInvitationIntent", skip_serializing_if = "Option::is_none")]
    pub delete_invitation_intent: Option<Box<models::DeleteInvitationIntent>>,
    #[serde(rename = "deleteOrganizationIntent", skip_serializing_if = "Option::is_none")]
    pub delete_organization_intent: Option<Box<models::DeleteOrganizationIntent>>,
    #[serde(rename = "deletePolicyIntent", skip_serializing_if = "Option::is_none")]
    pub delete_policy_intent: Option<Box<models::DeletePolicyIntent>>,
    #[serde(rename = "createUserTagIntent", skip_serializing_if = "Option::is_none")]
    pub create_user_tag_intent: Option<Box<models::CreateUserTagIntent>>,
    #[serde(rename = "deleteUserTagsIntent", skip_serializing_if = "Option::is_none")]
    pub delete_user_tags_intent: Option<Box<models::DeleteUserTagsIntent>>,
    #[serde(rename = "signTransactionIntent", skip_serializing_if = "Option::is_none")]
    pub sign_transaction_intent: Option<Box<models::SignTransactionIntent>>,
    #[serde(rename = "createApiKeysIntent", skip_serializing_if = "Option::is_none")]
    pub create_api_keys_intent: Option<Box<models::CreateApiKeysIntent>>,
    #[serde(rename = "deleteApiKeysIntent", skip_serializing_if = "Option::is_none")]
    pub delete_api_keys_intent: Option<Box<models::DeleteApiKeysIntent>>,
    #[serde(rename = "approveActivityIntent", skip_serializing_if = "Option::is_none")]
    pub approve_activity_intent: Option<Box<models::ApproveActivityIntent>>,
    #[serde(rename = "rejectActivityIntent", skip_serializing_if = "Option::is_none")]
    pub reject_activity_intent: Option<Box<models::RejectActivityIntent>>,
    #[serde(rename = "createPrivateKeyTagIntent", skip_serializing_if = "Option::is_none")]
    pub create_private_key_tag_intent: Option<Box<models::CreatePrivateKeyTagIntent>>,
    #[serde(rename = "deletePrivateKeyTagsIntent", skip_serializing_if = "Option::is_none")]
    pub delete_private_key_tags_intent: Option<Box<models::DeletePrivateKeyTagsIntent>>,
    #[serde(rename = "createPolicyIntentV2", skip_serializing_if = "Option::is_none")]
    pub create_policy_intent_v2: Option<Box<models::CreatePolicyIntentV2>>,
    #[serde(rename = "setPaymentMethodIntent", skip_serializing_if = "Option::is_none")]
    pub set_payment_method_intent: Option<Box<models::SetPaymentMethodIntent>>,
    #[serde(rename = "activateBillingTierIntent", skip_serializing_if = "Option::is_none")]
    pub activate_billing_tier_intent: Option<Box<models::ActivateBillingTierIntent>>,
    #[serde(rename = "deletePaymentMethodIntent", skip_serializing_if = "Option::is_none")]
    pub delete_payment_method_intent: Option<Box<models::DeletePaymentMethodIntent>>,
    #[serde(rename = "createPolicyIntentV3", skip_serializing_if = "Option::is_none")]
    pub create_policy_intent_v3: Option<Box<models::CreatePolicyIntentV3>>,
    #[serde(rename = "createApiOnlyUsersIntent", skip_serializing_if = "Option::is_none")]
    pub create_api_only_users_intent: Option<Box<models::CreateApiOnlyUsersIntent>>,
    #[serde(rename = "updateRootQuorumIntent", skip_serializing_if = "Option::is_none")]
    pub update_root_quorum_intent: Option<Box<models::UpdateRootQuorumIntent>>,
    #[serde(rename = "updateUserTagIntent", skip_serializing_if = "Option::is_none")]
    pub update_user_tag_intent: Option<Box<models::UpdateUserTagIntent>>,
    #[serde(rename = "updatePrivateKeyTagIntent", skip_serializing_if = "Option::is_none")]
    pub update_private_key_tag_intent: Option<Box<models::UpdatePrivateKeyTagIntent>>,
    #[serde(rename = "createAuthenticatorsIntentV2", skip_serializing_if = "Option::is_none")]
    pub create_authenticators_intent_v2: Option<Box<models::CreateAuthenticatorsIntentV2>>,
    #[serde(rename = "acceptInvitationIntentV2", skip_serializing_if = "Option::is_none")]
    pub accept_invitation_intent_v2: Option<Box<models::AcceptInvitationIntentV2>>,
    #[serde(rename = "createOrganizationIntentV2", skip_serializing_if = "Option::is_none")]
    pub create_organization_intent_v2: Option<Box<models::CreateOrganizationIntentV2>>,
    #[serde(rename = "createUsersIntentV2", skip_serializing_if = "Option::is_none")]
    pub create_users_intent_v2: Option<Box<models::CreateUsersIntentV2>>,
    #[serde(rename = "createSubOrganizationIntent", skip_serializing_if = "Option::is_none")]
    pub create_sub_organization_intent: Option<Box<models::CreateSubOrganizationIntent>>,
    #[serde(rename = "createSubOrganizationIntentV2", skip_serializing_if = "Option::is_none")]
    pub create_sub_organization_intent_v2: Option<Box<models::CreateSubOrganizationIntentV2>>,
    #[serde(rename = "updateAllowedOriginsIntent", skip_serializing_if = "Option::is_none")]
    pub update_allowed_origins_intent: Option<Box<models::UpdateAllowedOriginsIntent>>,
    #[serde(rename = "createPrivateKeysIntentV2", skip_serializing_if = "Option::is_none")]
    pub create_private_keys_intent_v2: Option<Box<models::CreatePrivateKeysIntentV2>>,
    #[serde(rename = "updateUserIntent", skip_serializing_if = "Option::is_none")]
    pub update_user_intent: Option<Box<models::UpdateUserIntent>>,
    #[serde(rename = "updatePolicyIntent", skip_serializing_if = "Option::is_none")]
    pub update_policy_intent: Option<Box<models::UpdatePolicyIntent>>,
    #[serde(rename = "setPaymentMethodIntentV2", skip_serializing_if = "Option::is_none")]
    pub set_payment_method_intent_v2: Option<Box<models::SetPaymentMethodIntentV2>>,
    #[serde(rename = "createSubOrganizationIntentV3", skip_serializing_if = "Option::is_none")]
    pub create_sub_organization_intent_v3: Option<Box<models::CreateSubOrganizationIntentV3>>,
    #[serde(rename = "createWalletIntent", skip_serializing_if = "Option::is_none")]
    pub create_wallet_intent: Option<Box<models::CreateWalletIntent>>,
    #[serde(rename = "createWalletAccountsIntent", skip_serializing_if = "Option::is_none")]
    pub create_wallet_accounts_intent: Option<Box<models::CreateWalletAccountsIntent>>,
    #[serde(rename = "initUserEmailRecoveryIntent", skip_serializing_if = "Option::is_none")]
    pub init_user_email_recovery_intent: Option<Box<models::InitUserEmailRecoveryIntent>>,
    #[serde(rename = "recoverUserIntent", skip_serializing_if = "Option::is_none")]
    pub recover_user_intent: Option<Box<models::RecoverUserIntent>>,
    #[serde(rename = "setOrganizationFeatureIntent", skip_serializing_if = "Option::is_none")]
    pub set_organization_feature_intent: Option<Box<models::SetOrganizationFeatureIntent>>,
    #[serde(rename = "removeOrganizationFeatureIntent", skip_serializing_if = "Option::is_none")]
    pub remove_organization_feature_intent: Option<Box<models::RemoveOrganizationFeatureIntent>>,
    #[serde(rename = "signRawPayloadIntentV2", skip_serializing_if = "Option::is_none")]
    pub sign_raw_payload_intent_v2: Option<Box<models::SignRawPayloadIntentV2>>,
    #[serde(rename = "signTransactionIntentV2", skip_serializing_if = "Option::is_none")]
    pub sign_transaction_intent_v2: Option<Box<models::SignTransactionIntentV2>>,
    #[serde(rename = "exportPrivateKeyIntent", skip_serializing_if = "Option::is_none")]
    pub export_private_key_intent: Option<Box<models::ExportPrivateKeyIntent>>,
    #[serde(rename = "exportWalletIntent", skip_serializing_if = "Option::is_none")]
    pub export_wallet_intent: Option<Box<models::ExportWalletIntent>>,
    #[serde(rename = "createSubOrganizationIntentV4", skip_serializing_if = "Option::is_none")]
    pub create_sub_organization_intent_v4: Option<Box<models::CreateSubOrganizationIntentV4>>,
    #[serde(rename = "emailAuthIntent", skip_serializing_if = "Option::is_none")]
    pub email_auth_intent: Option<Box<models::EmailAuthIntent>>,
    #[serde(rename = "exportWalletAccountIntent", skip_serializing_if = "Option::is_none")]
    pub export_wallet_account_intent: Option<Box<models::ExportWalletAccountIntent>>,
    #[serde(rename = "initImportWalletIntent", skip_serializing_if = "Option::is_none")]
    pub init_import_wallet_intent: Option<Box<models::InitImportWalletIntent>>,
    #[serde(rename = "importWalletIntent", skip_serializing_if = "Option::is_none")]
    pub import_wallet_intent: Option<Box<models::ImportWalletIntent>>,
    #[serde(rename = "initImportPrivateKeyIntent", skip_serializing_if = "Option::is_none")]
    pub init_import_private_key_intent: Option<Box<models::InitImportPrivateKeyIntent>>,
    #[serde(rename = "importPrivateKeyIntent", skip_serializing_if = "Option::is_none")]
    pub import_private_key_intent: Option<Box<models::ImportPrivateKeyIntent>>,
    #[serde(rename = "createPoliciesIntent", skip_serializing_if = "Option::is_none")]
    pub create_policies_intent: Option<Box<models::CreatePoliciesIntent>>,
    #[serde(rename = "signRawPayloadsIntent", skip_serializing_if = "Option::is_none")]
    pub sign_raw_payloads_intent: Option<Box<models::SignRawPayloadsIntent>>,
    #[serde(rename = "createReadOnlySessionIntent", skip_serializing_if = "Option::is_none")]
    pub create_read_only_session_intent: Option<serde_json::Value>,
    #[serde(rename = "createOauthProvidersIntent", skip_serializing_if = "Option::is_none")]
    pub create_oauth_providers_intent: Option<Box<models::CreateOauthProvidersIntent>>,
    #[serde(rename = "deleteOauthProvidersIntent", skip_serializing_if = "Option::is_none")]
    pub delete_oauth_providers_intent: Option<Box<models::DeleteOauthProvidersIntent>>,
    #[serde(rename = "createSubOrganizationIntentV5", skip_serializing_if = "Option::is_none")]
    pub create_sub_organization_intent_v5: Option<Box<models::CreateSubOrganizationIntentV5>>,
    #[serde(rename = "oauthIntent", skip_serializing_if = "Option::is_none")]
    pub oauth_intent: Option<Box<models::OauthIntent>>,
    #[serde(rename = "createApiKeysIntentV2", skip_serializing_if = "Option::is_none")]
    pub create_api_keys_intent_v2: Option<Box<models::CreateApiKeysIntentV2>>,
    #[serde(rename = "createReadWriteSessionIntent", skip_serializing_if = "Option::is_none")]
    pub create_read_write_session_intent: Option<Box<models::CreateReadWriteSessionIntent>>,
    #[serde(rename = "emailAuthIntentV2", skip_serializing_if = "Option::is_none")]
    pub email_auth_intent_v2: Option<Box<models::EmailAuthIntentV2>>,
    #[serde(rename = "createSubOrganizationIntentV6", skip_serializing_if = "Option::is_none")]
    pub create_sub_organization_intent_v6: Option<Box<models::CreateSubOrganizationIntentV6>>,
    #[serde(rename = "deletePrivateKeysIntent", skip_serializing_if = "Option::is_none")]
    pub delete_private_keys_intent: Option<Box<models::DeletePrivateKeysIntent>>,
    #[serde(rename = "deleteWalletsIntent", skip_serializing_if = "Option::is_none")]
    pub delete_wallets_intent: Option<Box<models::DeleteWalletsIntent>>,
    #[serde(rename = "createReadWriteSessionIntentV2", skip_serializing_if = "Option::is_none")]
    pub create_read_write_session_intent_v2: Option<Box<models::CreateReadWriteSessionIntentV2>>,
    #[serde(rename = "deleteSubOrganizationIntent", skip_serializing_if = "Option::is_none")]
    pub delete_sub_organization_intent: Option<Box<models::DeleteSubOrganizationIntent>>,
    #[serde(rename = "initOtpAuthIntent", skip_serializing_if = "Option::is_none")]
    pub init_otp_auth_intent: Option<Box<models::InitOtpAuthIntent>>,
    #[serde(rename = "otpAuthIntent", skip_serializing_if = "Option::is_none")]
    pub otp_auth_intent: Option<Box<models::OtpAuthIntent>>,
    #[serde(rename = "createSubOrganizationIntentV7", skip_serializing_if = "Option::is_none")]
    pub create_sub_organization_intent_v7: Option<Box<models::CreateSubOrganizationIntentV7>>,
    #[serde(rename = "updateWalletIntent", skip_serializing_if = "Option::is_none")]
    pub update_wallet_intent: Option<Box<models::UpdateWalletIntent>>,
}

impl Intent {
    pub fn new() -> Intent {
        Intent {
            create_organization_intent: None,
            create_authenticators_intent: None,
            create_users_intent: None,
            create_private_keys_intent: None,
            sign_raw_payload_intent: None,
            create_invitations_intent: None,
            accept_invitation_intent: None,
            create_policy_intent: None,
            disable_private_key_intent: None,
            delete_users_intent: None,
            delete_authenticators_intent: None,
            delete_invitation_intent: None,
            delete_organization_intent: None,
            delete_policy_intent: None,
            create_user_tag_intent: None,
            delete_user_tags_intent: None,
            sign_transaction_intent: None,
            create_api_keys_intent: None,
            delete_api_keys_intent: None,
            approve_activity_intent: None,
            reject_activity_intent: None,
            create_private_key_tag_intent: None,
            delete_private_key_tags_intent: None,
            create_policy_intent_v2: None,
            set_payment_method_intent: None,
            activate_billing_tier_intent: None,
            delete_payment_method_intent: None,
            create_policy_intent_v3: None,
            create_api_only_users_intent: None,
            update_root_quorum_intent: None,
            update_user_tag_intent: None,
            update_private_key_tag_intent: None,
            create_authenticators_intent_v2: None,
            accept_invitation_intent_v2: None,
            create_organization_intent_v2: None,
            create_users_intent_v2: None,
            create_sub_organization_intent: None,
            create_sub_organization_intent_v2: None,
            update_allowed_origins_intent: None,
            create_private_keys_intent_v2: None,
            update_user_intent: None,
            update_policy_intent: None,
            set_payment_method_intent_v2: None,
            create_sub_organization_intent_v3: None,
            create_wallet_intent: None,
            create_wallet_accounts_intent: None,
            init_user_email_recovery_intent: None,
            recover_user_intent: None,
            set_organization_feature_intent: None,
            remove_organization_feature_intent: None,
            sign_raw_payload_intent_v2: None,
            sign_transaction_intent_v2: None,
            export_private_key_intent: None,
            export_wallet_intent: None,
            create_sub_organization_intent_v4: None,
            email_auth_intent: None,
            export_wallet_account_intent: None,
            init_import_wallet_intent: None,
            import_wallet_intent: None,
            init_import_private_key_intent: None,
            import_private_key_intent: None,
            create_policies_intent: None,
            sign_raw_payloads_intent: None,
            create_read_only_session_intent: None,
            create_oauth_providers_intent: None,
            delete_oauth_providers_intent: None,
            create_sub_organization_intent_v5: None,
            oauth_intent: None,
            create_api_keys_intent_v2: None,
            create_read_write_session_intent: None,
            email_auth_intent_v2: None,
            create_sub_organization_intent_v6: None,
            delete_private_keys_intent: None,
            delete_wallets_intent: None,
            create_read_write_session_intent_v2: None,
            delete_sub_organization_intent: None,
            init_otp_auth_intent: None,
            otp_auth_intent: None,
            create_sub_organization_intent_v7: None,
            update_wallet_intent: None,
        }
    }
}

