/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvitationParams {
    /// The name of the intended Invitation recipient.
    #[serde(rename = "receiverUserName")]
    pub receiver_user_name: String,
    /// The email address of the intended Invitation recipient.
    #[serde(rename = "receiverUserEmail")]
    pub receiver_user_email: String,
    /// A list of tags assigned to the Invitation recipient.
    #[serde(rename = "receiverUserTags")]
    pub receiver_user_tags: Vec<String>,
    #[serde(rename = "accessType")]
    pub access_type: models::AccessType,
    /// Unique identifier for the Sender of an Invitation.
    #[serde(rename = "senderUserId")]
    pub sender_user_id: String,
}

impl InvitationParams {
    pub fn new(receiver_user_name: String, receiver_user_email: String, receiver_user_tags: Vec<String>, access_type: models::AccessType, sender_user_id: String) -> InvitationParams {
        InvitationParams {
            receiver_user_name,
            receiver_user_email,
            receiver_user_tags,
            access_type,
            sender_user_id,
        }
    }
}

