/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListUserTagsResponse {
    /// A list of User Tags
    #[serde(rename = "userTags")]
    pub user_tags: Vec<models::V1PeriodTag>,
}

impl ListUserTagsResponse {
    pub fn new(user_tags: Vec<models::V1PeriodTag>) -> ListUserTagsResponse {
        ListUserTagsResponse {
            user_tags,
        }
    }
}

