/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPrivateKeyTagsResponse {
    /// A list of Private Key Tags
    #[serde(rename = "privateKeyTags")]
    pub private_key_tags: Vec<models::V1PeriodTag>,
}

impl ListPrivateKeyTagsResponse {
    pub fn new(private_key_tags: Vec<models::V1PeriodTag>) -> ListPrivateKeyTagsResponse {
        ListPrivateKeyTagsResponse {
            private_key_tags,
        }
    }
}

