/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MnemonicLanguage {
    #[serde(rename = "MNEMONIC_LANGUAGE_ENGLISH")]
    MnemonicLanguageEnglish,
    #[serde(rename = "MNEMONIC_LANGUAGE_SIMPLIFIED_CHINESE")]
    MnemonicLanguageSimplifiedChinese,
    #[serde(rename = "MNEMONIC_LANGUAGE_TRADITIONAL_CHINESE")]
    MnemonicLanguageTraditionalChinese,
    #[serde(rename = "MNEMONIC_LANGUAGE_CZECH")]
    MnemonicLanguageCzech,
    #[serde(rename = "MNEMONIC_LANGUAGE_FRENCH")]
    MnemonicLanguageFrench,
    #[serde(rename = "MNEMONIC_LANGUAGE_ITALIAN")]
    MnemonicLanguageItalian,
    #[serde(rename = "MNEMONIC_LANGUAGE_JAPANESE")]
    MnemonicLanguageJapanese,
    #[serde(rename = "MNEMONIC_LANGUAGE_KOREAN")]
    MnemonicLanguageKorean,
    #[serde(rename = "MNEMONIC_LANGUAGE_SPANISH")]
    MnemonicLanguageSpanish,

}

impl std::fmt::Display for MnemonicLanguage {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MnemonicLanguageEnglish => write!(f, "MNEMONIC_LANGUAGE_ENGLISH"),
            Self::MnemonicLanguageSimplifiedChinese => write!(f, "MNEMONIC_LANGUAGE_SIMPLIFIED_CHINESE"),
            Self::MnemonicLanguageTraditionalChinese => write!(f, "MNEMONIC_LANGUAGE_TRADITIONAL_CHINESE"),
            Self::MnemonicLanguageCzech => write!(f, "MNEMONIC_LANGUAGE_CZECH"),
            Self::MnemonicLanguageFrench => write!(f, "MNEMONIC_LANGUAGE_FRENCH"),
            Self::MnemonicLanguageItalian => write!(f, "MNEMONIC_LANGUAGE_ITALIAN"),
            Self::MnemonicLanguageJapanese => write!(f, "MNEMONIC_LANGUAGE_JAPANESE"),
            Self::MnemonicLanguageKorean => write!(f, "MNEMONIC_LANGUAGE_KOREAN"),
            Self::MnemonicLanguageSpanish => write!(f, "MNEMONIC_LANGUAGE_SPANISH"),
        }
    }
}

impl Default for MnemonicLanguage {
    fn default() -> MnemonicLanguage {
        Self::MnemonicLanguageEnglish
    }
}

