/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OauthRequest {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Timestamp (in milliseconds) of the request, used to verify liveness of user requests.
    #[serde(rename = "timestampMs")]
    pub timestamp_ms: String,
    /// Unique identifier for a given Organization.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    #[serde(rename = "parameters")]
    pub parameters: Box<models::OauthIntent>,
}

impl OauthRequest {
    pub fn new(r#type: Type, timestamp_ms: String, organization_id: String, parameters: models::OauthIntent) -> OauthRequest {
        OauthRequest {
            r#type,
            timestamp_ms,
            organization_id,
            parameters: Box::new(parameters),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ACTIVITY_TYPE_OAUTH")]
    ActivityTypeOauth,
}

impl Default for Type {
    fn default() -> Type {
        Self::ActivityTypeOauth
    }
}

