/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OauthProvider {
    /// Unique identifier for an OAuth Provider
    #[serde(rename = "providerId")]
    pub provider_id: String,
    /// Human-readable name to identify a Provider.
    #[serde(rename = "providerName")]
    pub provider_name: String,
    /// The issuer of the token, typically a URL indicating the authentication server, e.g https://accounts.google.com
    #[serde(rename = "issuer")]
    pub issuer: String,
    /// Expected audience ('aud' attribute of the signed token) which represents the app ID
    #[serde(rename = "audience")]
    pub audience: String,
    /// Expected subject ('sub' attribute of the signed token) which represents the user ID
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
}

impl OauthProvider {
    pub fn new(provider_id: String, provider_name: String, issuer: String, audience: String, subject: String, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, updated_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp) -> OauthProvider {
        OauthProvider {
            provider_id,
            provider_name,
            issuer,
            audience,
            subject,
            created_at: Box::new(created_at),
            updated_at: Box::new(updated_at),
        }
    }
}

