/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OauthProviderParams {
    /// Human-readable name to identify a Provider.
    #[serde(rename = "providerName")]
    pub provider_name: String,
    /// Base64 encoded OIDC token
    #[serde(rename = "oidcToken")]
    pub oidc_token: String,
}

impl OauthProviderParams {
    pub fn new(provider_name: String, oidc_token: String) -> OauthProviderParams {
        OauthProviderParams {
            provider_name,
            oidc_token,
        }
    }
}

