/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OauthIntent {
    /// Base64 encoded OIDC token
    #[serde(rename = "oidcToken")]
    pub oidc_token: String,
    /// Client-side public key generated by the user, to which the oauth bundle (credentials) will be encrypted.
    #[serde(rename = "targetPublicKey")]
    pub target_public_key: String,
    /// Optional human-readable name for an API Key. If none provided, default to Oauth - <Timestamp>
    #[serde(rename = "apiKeyName", skip_serializing_if = "Option::is_none")]
    pub api_key_name: Option<String>,
    /// Expiration window (in seconds) indicating how long the API key is valid. If not provided, a default of 15 minutes will be used.
    #[serde(rename = "expirationSeconds", skip_serializing_if = "Option::is_none")]
    pub expiration_seconds: Option<String>,
}

impl OauthIntent {
    pub fn new(oidc_token: String, target_public_key: String) -> OauthIntent {
        OauthIntent {
            oidc_token,
            target_public_key,
            api_key_name: None,
            expiration_seconds: None,
        }
    }
}

