/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "OPERATOR_EQUAL")]
    OperatorEqual,
    #[serde(rename = "OPERATOR_MORE_THAN")]
    OperatorMoreThan,
    #[serde(rename = "OPERATOR_MORE_THAN_OR_EQUAL")]
    OperatorMoreThanOrEqual,
    #[serde(rename = "OPERATOR_LESS_THAN")]
    OperatorLessThan,
    #[serde(rename = "OPERATOR_LESS_THAN_OR_EQUAL")]
    OperatorLessThanOrEqual,
    #[serde(rename = "OPERATOR_CONTAINS")]
    OperatorContains,
    #[serde(rename = "OPERATOR_NOT_EQUAL")]
    OperatorNotEqual,
    #[serde(rename = "OPERATOR_IN")]
    OperatorIn,
    #[serde(rename = "OPERATOR_NOT_IN")]
    OperatorNotIn,
    #[serde(rename = "OPERATOR_CONTAINS_ONE")]
    OperatorContainsOne,
    #[serde(rename = "OPERATOR_CONTAINS_ALL")]
    OperatorContainsAll,

}

impl std::fmt::Display for Operator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OperatorEqual => write!(f, "OPERATOR_EQUAL"),
            Self::OperatorMoreThan => write!(f, "OPERATOR_MORE_THAN"),
            Self::OperatorMoreThanOrEqual => write!(f, "OPERATOR_MORE_THAN_OR_EQUAL"),
            Self::OperatorLessThan => write!(f, "OPERATOR_LESS_THAN"),
            Self::OperatorLessThanOrEqual => write!(f, "OPERATOR_LESS_THAN_OR_EQUAL"),
            Self::OperatorContains => write!(f, "OPERATOR_CONTAINS"),
            Self::OperatorNotEqual => write!(f, "OPERATOR_NOT_EQUAL"),
            Self::OperatorIn => write!(f, "OPERATOR_IN"),
            Self::OperatorNotIn => write!(f, "OPERATOR_NOT_IN"),
            Self::OperatorContainsOne => write!(f, "OPERATOR_CONTAINS_ONE"),
            Self::OperatorContainsAll => write!(f, "OPERATOR_CONTAINS_ALL"),
        }
    }
}

impl Default for Operator {
    fn default() -> Operator {
        Self::OperatorEqual
    }
}

