/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OtpAuthIntent {
    /// ID representing the result of an init OTP activity.
    #[serde(rename = "otpId")]
    pub otp_id: String,
    /// 6 digit OTP code sent out to a user's contact (email or SMS)
    #[serde(rename = "otpCode")]
    pub otp_code: String,
    /// Client-side public key generated by the user, to which the OTP bundle (credentials) will be encrypted.
    #[serde(rename = "targetPublicKey", skip_serializing_if = "Option::is_none")]
    pub target_public_key: Option<String>,
    /// Optional human-readable name for an API Key. If none provided, default to OTP Auth - <Timestamp>
    #[serde(rename = "apiKeyName", skip_serializing_if = "Option::is_none")]
    pub api_key_name: Option<String>,
    /// Expiration window (in seconds) indicating how long the API key is valid. If not provided, a default of 15 minutes will be used.
    #[serde(rename = "expirationSeconds", skip_serializing_if = "Option::is_none")]
    pub expiration_seconds: Option<String>,
    /// Invalidate all other previously generated OTP Auth API keys
    #[serde(rename = "invalidateExisting", skip_serializing_if = "Option::is_none")]
    pub invalidate_existing: Option<bool>,
}

impl OtpAuthIntent {
    pub fn new(otp_id: String, otp_code: String) -> OtpAuthIntent {
        OtpAuthIntent {
            otp_id,
            otp_code,
            target_public_key: None,
            api_key_name: None,
            expiration_seconds: None,
            invalidate_existing: None,
        }
    }
}

