/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pagination {
    /// A limit of the number of object to be returned, between 1 and 100. Defaults to 10.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<String>,
    /// A pagination cursor. This is an object ID that enables you to fetch all objects before this ID.
    #[serde(rename = "before", skip_serializing_if = "Option::is_none")]
    pub before: Option<String>,
    /// A pagination cursor. This is an object ID that enables you to fetch all objects after this ID.
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
}

impl Pagination {
    pub fn new() -> Pagination {
        Pagination {
            limit: None,
            before: None,
            after: None,
        }
    }
}

