/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PathFormat {
    #[serde(rename = "PATH_FORMAT_BIP32")]
    PathFormatBip32,

}

impl std::fmt::Display for PathFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PathFormatBip32 => write!(f, "PATH_FORMAT_BIP32"),
        }
    }
}

impl Default for PathFormat {
    fn default() -> PathFormat {
        Self::PathFormatBip32
    }
}

