/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayloadEncoding {
    #[serde(rename = "PAYLOAD_ENCODING_HEXADECIMAL")]
    PayloadEncodingHexadecimal,
    #[serde(rename = "PAYLOAD_ENCODING_TEXT_UTF8")]
    PayloadEncodingTextUtf8,

}

impl std::fmt::Display for PayloadEncoding {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PayloadEncodingHexadecimal => write!(f, "PAYLOAD_ENCODING_HEXADECIMAL"),
            Self::PayloadEncodingTextUtf8 => write!(f, "PAYLOAD_ENCODING_TEXT_UTF8"),
        }
    }
}

impl Default for PayloadEncoding {
    fn default() -> PayloadEncoding {
        Self::PayloadEncodingHexadecimal
    }
}

