/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Policy {
    /// Unique identifier for a given Policy.
    #[serde(rename = "policyId")]
    pub policy_id: String,
    /// Human-readable name for a Policy.
    #[serde(rename = "policyName")]
    pub policy_name: String,
    #[serde(rename = "effect")]
    pub effect: models::Effect,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    /// Human-readable notes added by a User to describe a particular policy.
    #[serde(rename = "notes")]
    pub notes: String,
    /// A consensus expression that evalutes to true or false.
    #[serde(rename = "consensus")]
    pub consensus: String,
    /// A condition expression that evalutes to true or false.
    #[serde(rename = "condition")]
    pub condition: String,
}

impl Policy {
    pub fn new(policy_id: String, policy_name: String, effect: models::Effect, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, updated_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, notes: String, consensus: String, condition: String) -> Policy {
        Policy {
            policy_id,
            policy_name,
            effect,
            created_at: Box::new(created_at),
            updated_at: Box::new(updated_at),
            notes,
            consensus,
            condition,
        }
    }
}

