/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateKeyParams {
    /// Human-readable name for a Private Key.
    #[serde(rename = "privateKeyName")]
    pub private_key_name: String,
    #[serde(rename = "curve")]
    pub curve: models::Curve,
    /// A list of Private Key Tag IDs.
    #[serde(rename = "privateKeyTags")]
    pub private_key_tags: Vec<String>,
    /// Cryptocurrency-specific formats for a derived address (e.g., Ethereum).
    #[serde(rename = "addressFormats")]
    pub address_formats: Vec<models::AddressFormat>,
}

impl PrivateKeyParams {
    pub fn new(private_key_name: String, curve: models::Curve, private_key_tags: Vec<String>, address_formats: Vec<models::AddressFormat>) -> PrivateKeyParams {
        PrivateKeyParams {
            private_key_name,
            curve,
            private_key_tags,
            address_formats,
        }
    }
}

