/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateKey {
    /// Unique identifier for a given Private Key.
    #[serde(rename = "privateKeyId")]
    pub private_key_id: String,
    /// The public component of a cryptographic key pair used to sign messages and transactions.
    #[serde(rename = "publicKey")]
    pub public_key: String,
    /// Human-readable name for a Private Key.
    #[serde(rename = "privateKeyName")]
    pub private_key_name: String,
    #[serde(rename = "curve")]
    pub curve: models::Curve,
    /// Derived cryptocurrency addresses for a given Private Key.
    #[serde(rename = "addresses")]
    pub addresses: Vec<models::DataPeriodV1PeriodAddress>,
    /// A list of Private Key Tag IDs.
    #[serde(rename = "privateKeyTags")]
    pub private_key_tags: Vec<String>,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    /// True when a given Private Key is exported, false otherwise.
    #[serde(rename = "exported")]
    pub exported: bool,
    /// True when a given Private Key is imported, false otherwise.
    #[serde(rename = "imported")]
    pub imported: bool,
}

impl PrivateKey {
    pub fn new(private_key_id: String, public_key: String, private_key_name: String, curve: models::Curve, addresses: Vec<models::DataPeriodV1PeriodAddress>, private_key_tags: Vec<String>, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, updated_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, exported: bool, imported: bool) -> PrivateKey {
        PrivateKey {
            private_key_id,
            public_key,
            private_key_name,
            curve,
            addresses,
            private_key_tags,
            created_at: Box::new(created_at),
            updated_at: Box::new(updated_at),
            exported,
            imported,
        }
    }
}

