/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicKeyCredentialWithAttestation {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "rawId")]
    pub raw_id: String,
    #[serde(rename = "authenticatorAttachment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub authenticator_attachment: Option<Option<AuthenticatorAttachment>>,
    #[serde(rename = "response")]
    pub response: Box<models::AuthenticatorAttestationResponse>,
    #[serde(rename = "clientExtensionResults")]
    pub client_extension_results: Box<models::SimpleClientExtensionResults>,
}

impl PublicKeyCredentialWithAttestation {
    pub fn new(id: String, r#type: Type, raw_id: String, response: models::AuthenticatorAttestationResponse, client_extension_results: models::SimpleClientExtensionResults) -> PublicKeyCredentialWithAttestation {
        PublicKeyCredentialWithAttestation {
            id,
            r#type,
            raw_id,
            authenticator_attachment: None,
            response: Box::new(response),
            client_extension_results: Box::new(client_extension_results),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "public-key")]
    PublicKey,
}

impl Default for Type {
    fn default() -> Type {
        Self::PublicKey
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticatorAttachment {
    #[serde(rename = "cross-platform")]
    CrossPlatform,
    #[serde(rename = "platform")]
    Platform,
}

impl Default for AuthenticatorAttachment {
    fn default() -> AuthenticatorAttachment {
        Self::CrossPlatform
    }
}

