/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecoverUserIntent {
    #[serde(rename = "authenticator")]
    pub authenticator: Box<models::AuthenticatorParamsV2>,
    /// Unique identifier for the user performing recovery.
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl RecoverUserIntent {
    pub fn new(authenticator: models::AuthenticatorParamsV2, user_id: String) -> RecoverUserIntent {
        RecoverUserIntent {
            authenticator: Box::new(authenticator),
            user_id,
        }
    }
}

