/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveOrganizationFeatureIntent {
    #[serde(rename = "name")]
    pub name: models::FeatureName,
}

impl RemoveOrganizationFeatureIntent {
    pub fn new(name: models::FeatureName) -> RemoveOrganizationFeatureIntent {
        RemoveOrganizationFeatureIntent {
            name,
        }
    }
}

