/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RootUserParamsV2 {
    /// Human-readable name for a User.
    #[serde(rename = "userName")]
    pub user_name: String,
    /// The user's email address.
    #[serde(rename = "userEmail", skip_serializing_if = "Option::is_none")]
    pub user_email: Option<String>,
    /// A list of API Key parameters.
    #[serde(rename = "apiKeys")]
    pub api_keys: Vec<models::ApiKeyParams>,
    /// A list of Authenticator parameters.
    #[serde(rename = "authenticators")]
    pub authenticators: Vec<models::AuthenticatorParamsV2>,
    /// A list of Oauth providers.
    #[serde(rename = "oauthProviders")]
    pub oauth_providers: Vec<models::OauthProviderParams>,
}

impl RootUserParamsV2 {
    pub fn new(user_name: String, api_keys: Vec<models::ApiKeyParams>, authenticators: Vec<models::AuthenticatorParamsV2>, oauth_providers: Vec<models::OauthProviderParams>) -> RootUserParamsV2 {
        RootUserParamsV2 {
            user_name,
            user_email: None,
            api_keys,
            authenticators,
            oauth_providers,
        }
    }
}

