/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetPaymentMethodIntentV2 {
    /// The id of the payment method that was created clientside.
    #[serde(rename = "paymentMethodId")]
    pub payment_method_id: String,
    /// The email that will receive invoices for the credit card.
    #[serde(rename = "cardHolderEmail")]
    pub card_holder_email: String,
    /// The name associated with the credit card.
    #[serde(rename = "cardHolderName")]
    pub card_holder_name: String,
}

impl SetPaymentMethodIntentV2 {
    pub fn new(payment_method_id: String, card_holder_email: String, card_holder_name: String) -> SetPaymentMethodIntentV2 {
        SetPaymentMethodIntentV2 {
            payment_method_id,
            card_holder_email,
            card_holder_name,
        }
    }
}

