/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetPaymentMethodIntent {
    /// The account number of the customer's credit card.
    #[serde(rename = "number")]
    pub number: String,
    /// The verification digits of the customer's credit card.
    #[serde(rename = "cvv")]
    pub cvv: String,
    /// The month that the credit card expires.
    #[serde(rename = "expiryMonth")]
    pub expiry_month: String,
    /// The year that the credit card expires.
    #[serde(rename = "expiryYear")]
    pub expiry_year: String,
    /// The email that will receive invoices for the credit card.
    #[serde(rename = "cardHolderEmail")]
    pub card_holder_email: String,
    /// The name associated with the credit card.
    #[serde(rename = "cardHolderName")]
    pub card_holder_name: String,
}

impl SetPaymentMethodIntent {
    pub fn new(number: String, cvv: String, expiry_month: String, expiry_year: String, card_holder_email: String, card_holder_name: String) -> SetPaymentMethodIntent {
        SetPaymentMethodIntent {
            number,
            cvv,
            expiry_month,
            expiry_year,
            card_holder_email,
            card_holder_name,
        }
    }
}

