/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetOrganizationFeatureIntent {
    #[serde(rename = "name")]
    pub name: models::FeatureName,
    /// Optional value for the feature. Will override existing values if feature is already set.
    #[serde(rename = "value")]
    pub value: String,
}

impl SetOrganizationFeatureIntent {
    pub fn new(name: models::FeatureName, value: String) -> SetOrganizationFeatureIntent {
        SetOrganizationFeatureIntent {
            name,
            value,
        }
    }
}

