/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignTransactionIntentV2 {
    /// A Wallet account address, Private Key address, or Private Key identifier.
    #[serde(rename = "signWith")]
    pub sign_with: String,
    /// Raw unsigned transaction to be signed
    #[serde(rename = "unsignedTransaction")]
    pub unsigned_transaction: String,
    #[serde(rename = "type")]
    pub r#type: models::TransactionType,
}

impl SignTransactionIntentV2 {
    pub fn new(sign_with: String, unsigned_transaction: String, r#type: models::TransactionType) -> SignTransactionIntentV2 {
        SignTransactionIntentV2 {
            sign_with,
            unsigned_transaction,
            r#type,
        }
    }
}

