/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignRawPayloadIntent {
    /// Unique identifier for a given Private Key.
    #[serde(rename = "privateKeyId")]
    pub private_key_id: String,
    /// Raw unsigned payload to be signed.
    #[serde(rename = "payload")]
    pub payload: String,
    #[serde(rename = "encoding")]
    pub encoding: models::PayloadEncoding,
    #[serde(rename = "hashFunction")]
    pub hash_function: models::HashFunction,
}

impl SignRawPayloadIntent {
    pub fn new(private_key_id: String, payload: String, encoding: models::PayloadEncoding, hash_function: models::HashFunction) -> SignRawPayloadIntent {
        SignRawPayloadIntent {
            private_key_id,
            payload,
            encoding,
            hash_function,
        }
    }
}

