/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignRawPayloadIntentV2 {
    /// A Wallet account address, Private Key address, or Private Key identifier.
    #[serde(rename = "signWith")]
    pub sign_with: String,
    /// Raw unsigned payload to be signed.
    #[serde(rename = "payload")]
    pub payload: String,
    #[serde(rename = "encoding")]
    pub encoding: models::PayloadEncoding,
    #[serde(rename = "hashFunction")]
    pub hash_function: models::HashFunction,
}

impl SignRawPayloadIntentV2 {
    pub fn new(sign_with: String, payload: String, encoding: models::PayloadEncoding, hash_function: models::HashFunction) -> SignRawPayloadIntentV2 {
        SignRawPayloadIntentV2 {
            sign_with,
            payload,
            encoding,
            hash_function,
        }
    }
}

