/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignTransactionIntent {
    /// Unique identifier for a given Private Key.
    #[serde(rename = "privateKeyId")]
    pub private_key_id: String,
    /// Raw unsigned transaction to be signed by a particular Private Key.
    #[serde(rename = "unsignedTransaction")]
    pub unsigned_transaction: String,
    #[serde(rename = "type")]
    pub r#type: models::TransactionType,
}

impl SignTransactionIntent {
    pub fn new(private_key_id: String, unsigned_transaction: String, r#type: models::TransactionType) -> SignTransactionIntent {
        SignTransactionIntent {
            private_key_id,
            unsigned_transaction,
            r#type,
        }
    }
}

