/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignRawPayloadsIntent {
    /// A Wallet account address, Private Key address, or Private Key identifier.
    #[serde(rename = "signWith")]
    pub sign_with: String,
    /// An array of raw unsigned payloads to be signed.
    #[serde(rename = "payloads")]
    pub payloads: Vec<String>,
    #[serde(rename = "encoding")]
    pub encoding: models::PayloadEncoding,
    #[serde(rename = "hashFunction")]
    pub hash_function: models::HashFunction,
}

impl SignRawPayloadsIntent {
    pub fn new(sign_with: String, payloads: Vec<String>, encoding: models::PayloadEncoding, hash_function: models::HashFunction) -> SignRawPayloadsIntent {
        SignRawPayloadsIntent {
            sign_with,
            payloads,
            encoding,
            hash_function,
        }
    }
}

