/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SmsCustomizationParams {
    /// Template containing references to .OtpCode i.e Your OTP is {{.OtpCode}}
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
}

impl SmsCustomizationParams {
    pub fn new() -> SmsCustomizationParams {
        SmsCustomizationParams {
            template: None,
        }
    }
}

