/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TagType {
    #[serde(rename = "TAG_TYPE_USER")]
    TagTypeUser,
    #[serde(rename = "TAG_TYPE_PRIVATE_KEY")]
    TagTypePrivateKey,

}

impl std::fmt::Display for TagType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TagTypeUser => write!(f, "TAG_TYPE_USER"),
            Self::TagTypePrivateKey => write!(f, "TAG_TYPE_PRIVATE_KEY"),
        }
    }
}

impl Default for TagType {
    fn default() -> TagType {
        Self::TagTypeUser
    }
}

