/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionType {
    #[serde(rename = "TRANSACTION_TYPE_ETHEREUM")]
    TransactionTypeEthereum,
    #[serde(rename = "TRANSACTION_TYPE_SOLANA")]
    TransactionTypeSolana,

}

impl std::fmt::Display for TransactionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TransactionTypeEthereum => write!(f, "TRANSACTION_TYPE_ETHEREUM"),
            Self::TransactionTypeSolana => write!(f, "TRANSACTION_TYPE_SOLANA"),
        }
    }
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::TransactionTypeEthereum
    }
}

