/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRootQuorumIntent {
    /// The threshold of unique approvals to reach quorum.
    #[serde(rename = "threshold")]
    pub threshold: i32,
    /// The unique identifiers of users who comprise the quorum set.
    #[serde(rename = "userIds")]
    pub user_ids: Vec<String>,
}

impl UpdateRootQuorumIntent {
    pub fn new(threshold: i32, user_ids: Vec<String>) -> UpdateRootQuorumIntent {
        UpdateRootQuorumIntent {
            threshold,
            user_ids,
        }
    }
}

