/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWalletIntent {
    /// Unique identifier for a given Wallet.
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    /// Human-readable name for a Wallet.
    #[serde(rename = "walletName", skip_serializing_if = "Option::is_none")]
    pub wallet_name: Option<String>,
}

impl UpdateWalletIntent {
    pub fn new(wallet_id: String) -> UpdateWalletIntent {
        UpdateWalletIntent {
            wallet_id,
            wallet_name: None,
        }
    }
}

