/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePolicyIntent {
    /// Unique identifier for a given Policy.
    #[serde(rename = "policyId")]
    pub policy_id: String,
    /// Human-readable name for a Policy.
    #[serde(rename = "policyName", skip_serializing_if = "Option::is_none")]
    pub policy_name: Option<String>,
    #[serde(rename = "policyEffect", skip_serializing_if = "Option::is_none")]
    pub policy_effect: Option<models::Effect>,
    /// The condition expression that triggers the Effect (optional).
    #[serde(rename = "policyCondition", skip_serializing_if = "Option::is_none")]
    pub policy_condition: Option<String>,
    /// The consensus expression that triggers the Effect (optional).
    #[serde(rename = "policyConsensus", skip_serializing_if = "Option::is_none")]
    pub policy_consensus: Option<String>,
    /// Accompanying notes for a Policy (optional).
    #[serde(rename = "policyNotes", skip_serializing_if = "Option::is_none")]
    pub policy_notes: Option<String>,
}

impl UpdatePolicyIntent {
    pub fn new(policy_id: String) -> UpdatePolicyIntent {
        UpdatePolicyIntent {
            policy_id,
            policy_name: None,
            policy_effect: None,
            policy_condition: None,
            policy_consensus: None,
            policy_notes: None,
        }
    }
}

