/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePrivateKeyTagIntent {
    /// Unique identifier for a given Private Key Tag.
    #[serde(rename = "privateKeyTagId")]
    pub private_key_tag_id: String,
    /// The new, human-readable name for the tag with the given ID.
    #[serde(rename = "newPrivateKeyTagName", skip_serializing_if = "Option::is_none")]
    pub new_private_key_tag_name: Option<String>,
    /// A list of Private Keys IDs to add this tag to.
    #[serde(rename = "addPrivateKeyIds")]
    pub add_private_key_ids: Vec<String>,
    /// A list of Private Key IDs to remove this tag from.
    #[serde(rename = "removePrivateKeyIds")]
    pub remove_private_key_ids: Vec<String>,
}

impl UpdatePrivateKeyTagIntent {
    pub fn new(private_key_tag_id: String, add_private_key_ids: Vec<String>, remove_private_key_ids: Vec<String>) -> UpdatePrivateKeyTagIntent {
        UpdatePrivateKeyTagIntent {
            private_key_tag_id,
            new_private_key_tag_name: None,
            add_private_key_ids,
            remove_private_key_ids,
        }
    }
}

