/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserTagIntent {
    /// Unique identifier for a given User Tag.
    #[serde(rename = "userTagId")]
    pub user_tag_id: String,
    /// The new, human-readable name for the tag with the given ID.
    #[serde(rename = "newUserTagName", skip_serializing_if = "Option::is_none")]
    pub new_user_tag_name: Option<String>,
    /// A list of User IDs to add this tag to.
    #[serde(rename = "addUserIds")]
    pub add_user_ids: Vec<String>,
    /// A list of User IDs to remove this tag from.
    #[serde(rename = "removeUserIds")]
    pub remove_user_ids: Vec<String>,
}

impl UpdateUserTagIntent {
    pub fn new(user_tag_id: String, add_user_ids: Vec<String>, remove_user_ids: Vec<String>) -> UpdateUserTagIntent {
        UpdateUserTagIntent {
            user_tag_id,
            new_user_tag_name: None,
            add_user_ids,
            remove_user_ids,
        }
    }
}

