/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAllowedOriginsIntent {
    /// Additional origins requests are allowed from besides Turnkey origins
    #[serde(rename = "allowedOrigins")]
    pub allowed_origins: Vec<String>,
}

impl UpdateAllowedOriginsIntent {
    pub fn new(allowed_origins: Vec<String>) -> UpdateAllowedOriginsIntent {
        UpdateAllowedOriginsIntent {
            allowed_origins,
        }
    }
}

