/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserIntent {
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Human-readable name for a User.
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
    /// The user's email address.
    #[serde(rename = "userEmail", skip_serializing_if = "Option::is_none")]
    pub user_email: Option<String>,
    /// An updated list of User Tags to apply to this User.
    #[serde(rename = "userTagIds", skip_serializing_if = "Option::is_none")]
    pub user_tag_ids: Option<Vec<String>>,
    /// The user's phone number in E.164 format e.g. +13214567890
    #[serde(rename = "userPhoneNumber", skip_serializing_if = "Option::is_none")]
    pub user_phone_number: Option<String>,
}

impl UpdateUserIntent {
    pub fn new(user_id: String) -> UpdateUserIntent {
        UpdateUserIntent {
            user_id,
            user_name: None,
            user_email: None,
            user_tag_ids: None,
            user_phone_number: None,
        }
    }
}

