/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Human-readable name for a User.
    #[serde(rename = "userName")]
    pub user_name: String,
    /// The user's email address.
    #[serde(rename = "userEmail", skip_serializing_if = "Option::is_none")]
    pub user_email: Option<String>,
    /// The user's phone number in E.164 format e.g. +13214567890
    #[serde(rename = "userPhoneNumber", skip_serializing_if = "Option::is_none")]
    pub user_phone_number: Option<String>,
    /// A list of Authenticator parameters.
    #[serde(rename = "authenticators")]
    pub authenticators: Vec<models::Authenticator>,
    /// A list of API Key parameters.
    #[serde(rename = "apiKeys")]
    pub api_keys: Vec<models::ApiKey>,
    /// A list of User Tag IDs.
    #[serde(rename = "userTags")]
    pub user_tags: Vec<String>,
    /// A list of Oauth Providers.
    #[serde(rename = "oauthProviders")]
    pub oauth_providers: Vec<models::OauthProvider>,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
}

impl User {
    pub fn new(user_id: String, user_name: String, authenticators: Vec<models::Authenticator>, api_keys: Vec<models::ApiKey>, user_tags: Vec<String>, oauth_providers: Vec<models::OauthProvider>, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, updated_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp) -> User {
        User {
            user_id,
            user_name,
            user_email: None,
            user_phone_number: None,
            authenticators,
            api_keys,
            user_tags,
            oauth_providers,
            created_at: Box::new(created_at),
            updated_at: Box::new(updated_at),
        }
    }
}

