/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserParams {
    /// Human-readable name for a User.
    #[serde(rename = "userName")]
    pub user_name: String,
    /// The user's email address.
    #[serde(rename = "userEmail", skip_serializing_if = "Option::is_none")]
    pub user_email: Option<String>,
    #[serde(rename = "accessType")]
    pub access_type: models::AccessType,
    /// A list of API Key parameters.
    #[serde(rename = "apiKeys")]
    pub api_keys: Vec<models::ApiKeyParams>,
    /// A list of Authenticator parameters.
    #[serde(rename = "authenticators")]
    pub authenticators: Vec<models::AuthenticatorParams>,
    /// A list of User Tag IDs.
    #[serde(rename = "userTags")]
    pub user_tags: Vec<String>,
}

impl UserParams {
    pub fn new(user_name: String, access_type: models::AccessType, api_keys: Vec<models::ApiKeyParams>, authenticators: Vec<models::AuthenticatorParams>, user_tags: Vec<String>) -> UserParams {
        UserParams {
            user_name,
            user_email: None,
            access_type,
            api_keys,
            authenticators,
            user_tags,
        }
    }
}

