/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodTag {
    /// Unique identifier for a given Tag.
    #[serde(rename = "tagId")]
    pub tag_id: String,
    /// Human-readable name for a Tag.
    #[serde(rename = "tagName")]
    pub tag_name: String,
    #[serde(rename = "tagType")]
    pub tag_type: models::TagType,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
}

impl V1PeriodTag {
    pub fn new(tag_id: String, tag_name: String, tag_type: models::TagType, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, updated_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp) -> V1PeriodTag {
        V1PeriodTag {
            tag_id,
            tag_name,
            tag_type,
            created_at: Box::new(created_at),
            updated_at: Box::new(updated_at),
        }
    }
}

