/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vote {
    /// Unique identifier for a given Vote object.
    #[serde(rename = "id")]
    pub id: String,
    /// Unique identifier for a given User.
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "user")]
    pub user: Box<models::User>,
    /// Unique identifier for a given Activity object.
    #[serde(rename = "activityId")]
    pub activity_id: String,
    #[serde(rename = "selection")]
    pub selection: Selection,
    /// The raw message being signed within a Vote.
    #[serde(rename = "message")]
    pub message: String,
    /// The public component of a cryptographic key pair used to sign messages and transactions.
    #[serde(rename = "publicKey")]
    pub public_key: String,
    /// The signature applied to a particular vote.
    #[serde(rename = "signature")]
    pub signature: String,
    /// Method used to produce a signature.
    #[serde(rename = "scheme")]
    pub scheme: String,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
}

impl Vote {
    pub fn new(id: String, user_id: String, user: models::User, activity_id: String, selection: Selection, message: String, public_key: String, signature: String, scheme: String, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp) -> Vote {
        Vote {
            id,
            user_id,
            user: Box::new(user),
            activity_id,
            selection,
            message,
            public_key,
            signature,
            scheme,
            created_at: Box::new(created_at),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Selection {
    #[serde(rename = "VOTE_SELECTION_APPROVED")]
    VoteSelectionApproved,
    #[serde(rename = "VOTE_SELECTION_REJECTED")]
    VoteSelectionRejected,
}

impl Default for Selection {
    fn default() -> Selection {
        Self::VoteSelectionApproved
    }
}

