/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletAccountParams {
    #[serde(rename = "curve")]
    pub curve: models::Curve,
    #[serde(rename = "pathFormat")]
    pub path_format: models::PathFormat,
    /// Path used to generate a wallet Account.
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "addressFormat")]
    pub address_format: models::AddressFormat,
}

impl WalletAccountParams {
    pub fn new(curve: models::Curve, path_format: models::PathFormat, path: String, address_format: models::AddressFormat) -> WalletAccountParams {
        WalletAccountParams {
            curve,
            path_format,
            path,
            address_format,
        }
    }
}

