/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletAccount {
    /// Unique identifier for a given Wallet Account.
    #[serde(rename = "walletAccountId")]
    pub wallet_account_id: String,
    /// The Organization the Account belongs to.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
    /// The Wallet the Account was derived from.
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "curve")]
    pub curve: models::Curve,
    #[serde(rename = "pathFormat")]
    pub path_format: models::PathFormat,
    /// Path used to generate the Account.
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "addressFormat")]
    pub address_format: models::AddressFormat,
    /// Address generated using the Wallet seed and Account parameters.
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
}

impl WalletAccount {
    pub fn new(wallet_account_id: String, organization_id: String, wallet_id: String, curve: models::Curve, path_format: models::PathFormat, path: String, address_format: models::AddressFormat, address: String, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, updated_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp) -> WalletAccount {
        WalletAccount {
            wallet_account_id,
            organization_id,
            wallet_id,
            curve,
            path_format,
            path,
            address_format,
            address,
            created_at: Box::new(created_at),
            updated_at: Box::new(updated_at),
        }
    }
}

