/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletParams {
    /// Human-readable name for a Wallet.
    #[serde(rename = "walletName")]
    pub wallet_name: String,
    /// A list of wallet Accounts.
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::WalletAccountParams>,
    /// Length of mnemonic to generate the Wallet seed. Defaults to 12. Accepted values: 12, 15, 18, 21, 24.
    #[serde(rename = "mnemonicLength", skip_serializing_if = "Option::is_none")]
    pub mnemonic_length: Option<i32>,
}

impl WalletParams {
    pub fn new(wallet_name: String, accounts: Vec<models::WalletAccountParams>) -> WalletParams {
        WalletParams {
            wallet_name,
            accounts,
            mnemonic_length: None,
        }
    }
}

