/*
 * API Reference
 *
 * Review our [API Introduction](../api-introduction) to get started.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Wallet {
    /// Unique identifier for a given Wallet.
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    /// Human-readable name for a Wallet.
    #[serde(rename = "walletName")]
    pub wallet_name: String,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    #[serde(rename = "updatedAt")]
    pub updated_at: Box<models::ExternalPeriodDataPeriodV1PeriodTimestamp>,
    /// True when a given Wallet is exported, false otherwise.
    #[serde(rename = "exported")]
    pub exported: bool,
    /// True when a given Wallet is imported, false otherwise.
    #[serde(rename = "imported")]
    pub imported: bool,
}

impl Wallet {
    pub fn new(wallet_id: String, wallet_name: String, created_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, updated_at: models::ExternalPeriodDataPeriodV1PeriodTimestamp, exported: bool, imported: bool) -> Wallet {
        Wallet {
            wallet_id,
            wallet_name,
            created_at: Box::new(created_at),
            updated_at: Box::new(updated_at),
            exported,
            imported,
        }
    }
}

